# Abstracts

For each subheading below, I'd like to write a short abstract of the topic, and then link to the relevant notebooks.

## linear_models

Classisc are classic for a reason and it is fair to say that the linear model is a classic. The linear model is the workhorse of modern modeling and is the foundation for many models. While many models might exceed the linear model in predictive power, establishing a good bearing in the linear model is a great place to start. In this chapter, we'll cover the basics of the general linear model and how you can apply it to your data situation, while showing you both standard functions for creating a model and the underlying functions that make it work.

## model_criticism

You can't trust a model until you know that it will work and that is where **model criticism** comes to save the day. Model criticism is the process of evaluating the **fit** of a model to the data. Not only will you learn how to determine if your regression and classification models will work on new data, but you will also see some visualuzation methods from the `DaLeX` package that will help you to understand how the variables within your model are (mis)behaving.  

## steps

With data in hand, what do you do next? The steps to creating a useful model often elude new and experienced modelers alike. In this chapter, we'll cover the steps to creating a model, from data cleaning to model criticism. We'll also cover some of the common pitfalls that you might encounter along the way.

## estimation

How do models actually work? In this chapter, we'll cover the basics of **estimation**. Estimation is the process of finding the best parameters for a model. We'll cover the basics of how to estimate a model, how to interpret the results, and how to use the results to make predictions.

## generalized_linear_models

How do you make a classic even better? You make it useful across different situations! In this chapter, you'll see how you can take the architecture of the linear model and extend it to different outcomes -- namely outcomes that are binomially distributed or poisson distributed. You will see how you can take a binomially-distributed, binary outcome like "bad or good" and create a **logistic regression**. If your outcome is a count, like "number of reviews", you'll be able to create a **poisson regression**.

## linear_model_extensions

Your standard linear model with a continuous outcome relies on means to fit a line through your data. What happens, though, if a mean doesn't work? Or maybe a straight line won't actually capture the relationship between your variables? What if you had groups that might behave differently in a model? In this chapter, you'll see how we can take our linear model and extend it to common data situations. You'll see how you can use quantile regression, generalized additive models, and mixed effects models to create a linear model that is better suited for specific data situations. 

## machine_learning

As fancy as machine learning might sound, it is really just a set of tools with roots in those regression models that you've already seen. Where these tools differ, however, is typically in the goals. In this chapter, you'll see how shifting our goal from inference to prediction can open up a whole new set of tools designed for maximizing predictive power. To make the most out of those models, you'll learn how regularization, cross-validation, and parameter tuning can help you achieve the best predictive power possible for your specific problem.

## ml_common_models

With the goals of machine learning in mind, you can turn your attention to models that are worth trying out. In this chapter, models from regularized models and tree-based models to neural networks will be covered. You'll see how we can test these more sophisticated models against a simmpler baseline model to see if the time and complexity offers you improved performance.

## ml_more
## data
## causal

You've heard the phrase, "Correlation does not equal causation" in every statistics class that you've ever taken. What if, though, you'd like to start down the path of causal modeling? In this chapter, you'll see the basic of causal models and how you can use them to estimate causal effects. You'll see how you can use various path diagrams to represent your causal model and how you can 
## misc_models
## bayes