# Acknowledgments



This work was supported by no grants or grad students, and it was done entirely in the spare time of the authors after their long days of work and teaching. We do not recommend this approach, but it appears we eventually got it done! But we could not have done this without the support of our families, who have been patient and understanding throughout the process.

In particular, Michael wishes to thank his wife Xilin, whose insights, humor, support, and especially patience, have been invaluable throughout the process. He'd also like to thank Rich Herrington, whose encouragement was the catalyst for his shift from psychology to data science many years ago. Michael also thanks his fellow consultants at the University of Michigan whose thoughtful discussions shaped much of his analytical thinking, as well as the folks at Strong Analytics and OneSix who supported his transition from academia to industry and made him much better at everything he does in the realm of data science. And finally, he would like to thank the many mentors in the statistical, machine learning, deep learning/AI, and programming communities, who never knew they were such a large influence but did much to expand his knowledge in many ways over the years.

Seth is grateful for the support and understanding of his wife Megan, and his fantastic kids, who never cease to bring him joy. He'd also like to thank his colleagues and students at Notre Dame who have supported his teaching antics and research shenanigans. He hopes that this book provides at least some evidence that he knows what he's talking about.


Together we'd like to thank those who helped with the book by providing comments and feedback, specifically: Malcolm Barrett, Isabella Gehment, Demetri Pananos, and Chelsea Parlett-Pellereti. Their insights and suggestions were invaluable in making this book a lot better. We'd also like to thank others who took the time for a quick glance to see what was going on and provide a brief comment here and there. Every contribution was appreciated.

Finally, we'd like to thank you, the reader, for taking the time to peruse this book. We hope you find it useful and informative, and that it helps you in your data science journey. If you have any feedback, please feel free to reach out to us. We'd love to hear from you.

Thank you!

[Michael & Seth]{.signoff}