# Dataset Descriptions {#sec-data-descript}

## Movie reviews {#sec-dd-movie-reviews}

The movie reviews dataset was a fun way to use an LLM to create data movie titles and reviews in a specific way, as well as other features. With features in hand, we then generated a rating outcome with specific feature-target relationships. It has 1000 rows and the following columns:

- title: The title of the movie
- review_year: The year the review was written
- age: The age of the reviewer
- children_in_home: The number of children in the reviewer's home
- education: The education level of the reviewer (Post-Graduate, Completed College, Completed High School)
- gender: The gender of the reviewer (male or female)
- work_status: The work status of the reviewer (Employed, Retired, Unemployed, Student)
- genre: The genre of the movie
- release_year: The year the movie was released
- length_minutes: The length of the movie in minutes
- season: The season the movie was released (e.g. Fall, Winter)
- total_reviews: The total number of reviews for the movie
- rating: The rating of the movie
- review_text: The text of the review
- word_count: The number of words in the review
- review_year_0: The review year starting from 0
- release_year_0: The release year starting from 0
- age_sc, length_minutes_sc, total_reviews_sc, word_count_sc: Scaled versions of age, length_minutes, total_reviews, and word_count
- rating_good: A binary version of rating, where 1 is a good rating (>= 3) and 0 is a bad rating (< 3)

The [raw movie reviews](https://raw.githubusercontent.com/m-clark/book-of-models/main/data/movie_reviews.csv) and [processed movie reviews](https://raw.githubusercontent.com/m-clark/book-of-models/main/data/movie_reviews_processed.csv) data sets are available directly in the book's repo.


## World Happiness Report {#sec-dd-world-happiness-report}

The [World Happiness Report](https://worldhappiness.report/) is a survey of the state of global happiness that ranks countries by how 'happy' their citizens perceive themselves to be.  You can also find additional in their [supplemental documentation](https://happiness-report.s3.amazonaws.com/2024/Ch2+Appendix.pdf).  Our 2018 data is from what was originally reported at that time (figure 2.2) and it also contains a life ladder score from the most recent survey, which is similar and very highly correlated.  

 The dataset contains the following columns:

- country: The country name
- year: The year of the survey
- life_ladder: The happiness score
- log_gdp_per_capita: The log of GDP per capita
- social_support: The social support score
- healthy_life_expectancy_at_birth: The healthy life expectancy at birth
- freedom_to_make_life_choices: The freedom to make life choices score
- generosity: The generosity score
- perceptions_of_corruption: The perceptions of corruption score
- positive_affect: The positive affect score
- negative_affect: The negative affect score
- confidence_in_national_government: The confidence in national government score
- happiness_score: The happiness score
- dystopia_residual: The dystopia residual score (difference from a 'least happy' country)

In addition there are standardized/scaled versions of the features, which are suffixed with `_sc`.

Data for [all years](https://raw.githubusercontent.com/m-clark/book-of-models/main/data/world_happiness_all_years.csv) and [2018 only](https://raw.githubusercontent.com/m-clark/book-of-models/main/data/world_happiness_2018.csv) are available directly in the book's repo.


## Heart Disease UCI {#sec-dd-heart-disease-uci}

Dataset from Kaggle: https://www.kaggle.com/ronitf/heart-disease-uci

This database contains 76 attributes, but all published experiments refer to using a subset of 14 of them. In particular, the Cleveland database is the only one that has been used by ML researchers to this date. Features and target were renamed to be more intelligible.

- age: age in years
- male: 'yes' or 'no'
- chest_pain_type: 'typical', 'atypical', 'non-anginal', 'asymptomatic'
- resting_bp: resting blood pressure (mm Hg)
- cholesterol: serum cholesterol (mg/dl)
- fasting_blood_sugar: '> 120 mg/dl' or '<= 120 mg/dl'
- resting_ecg: 'normal', 'left ventricular hypertrophy', 'ST-T wave abnormality'
- max_heart_rate: maximum heart rate achieved
- exercise_induced_angina: 'yes' or 'no'
- st_depression: ST depression induced by exercise relative to rest
- slope: 'upsloping', 'flat', 'downsloping'
- num_major_vessels: number of major vessels (0-3) colored by fluoroscopy
- thalassemia: 'normal', 'fixed defect', 'reversible defect'
- heart_disease: 'yes' or 'no'

The [processed data](https://raw.githubusercontent.com/m-clark/book-of-models/main/data/heart_disease_processed.csv) and [processed data with scaled numeric variables](https://raw.githubusercontent.com/m-clark/book-of-models/main/data/heart_disease_processed_numeric_sc.csv) are available directly in the book's repo.

## Fish {#sec-dd-fish}

State wildlife biologists want to model how many fish are being caught by fishermen at a state park. A very simple data set with a count target variable available for an exercise in the GLM chapter.  Also good if you want to try your hand at zero-inflated models.

- nofish: We've never seen this explained. Originally 0 and 1, 0 is equivalent to livebait == 'yes', so it may be whether the primary motivation of the camping trip is for fishing or not.
- livebait: whether live bait was used or not
- camper: whether or not they brought a camper
- persons: how many total persons on the trip
- child: how many children present
- count: number of fish caught

Available at tinyurl.com/fishcountdata.

<!-- 

## Heart Failure {#sec-dd-heart-failure}

Dataset from Davide Chicco, Giuseppe Jurman: “Machine learning can predict survival of patients with heart failure from serum creatinine and ejection fraction alone. BMC Medical Informatics and Decision Making 20, 16 (2020)

https://www.kaggle.com/datasets/andrewmvd/heart-failure-clinical-data

Cardiovascular diseases (CVDs) are the number 1 cause of death globally, taking an estimated 17.9 million lives each year, which accounts for 31% of all deaths worldwide.
Heart failure is a common event caused by CVDs and this dataset contains 12 features that can be used to predict mortality by heart failure.

Most cardiovascular diseases can be prevented by addressing behavioral risk factors such as tobacco use, unhealthy diet and obesity, physical inactivity and harmful use of alcohol using population-wide strategies.

People with cardiovascular disease or who are at high cardiovascular risk (due to the presence of one or more risk factors such as hypertension, diabetes, hyperlipidaemia or already established disease) need early detection and management wherein a machine learning model can be of great help.


- age: Age

anaemia: Decrease of red blood cells or hemoglobin (boolean)

creatinine_phosphokinase: Level of the CPK enzyme in the blood (mcg/L)

diabetes: If the patient has diabetes (boolean)

ejection_fraction: Percentage of blood leaving the heart at each contraction (percentage)

high_blood_pressure: If the patient has hypertension (boolean)

platelets: Platelets in the blood (kiloplatelets/mL)

serum_creatinine: Level of serum creatinine in the blood (mg/dL)

serum_sodium: Level of serum sodium in the blood (mEq/L)

sex: Woman or man (binary)

smoking: If the patient smokes or not (boolean)

time: Follow-up period (days)

DEATH_EVENT: If the patient deceased during the follow-up period (boolean)

For booleans:
Sex - Gender of patient Male = 1, Female =0  (renamed for our data)
Age - Age of patient
Diabetes - 0 = No, 1 = Yes
Anaemia - 0 = No, 1 = Yes
High_blood_pressure - 0 = No, 1 = Yes
Smoking - 0 = No, 1 = Yes
DEATH_EVENT - 0 = No, 1 = Yes 

-->