# Preface {.unnumbered #sec-preface}



```{r}
#| label: setup
#| include: false
library(tidyverse)

# set global options as needed
# options(
#     
# )

```

<!-- TODO: Quarto bug prints this twice in ToC; tried various header tricks to no avail. Also, not unnumbered by default for krantz.cls. -->

Hi there and welcome to our guide to models in data science! This resource is designed to provide you something useful whether you're a beginner looking to learn some fundamentals, or an experienced practitioner seeking a fresh perspective. Our goal is to equip you with a better understanding of models, how they work, and how to use them, including both basic and more advanced techniques.  We'll also show how they relate to one another to better empower you to apply them effectively in your own data-driven projects. With a focus on application while also presenting a deeper dive for those that prefer it, we aim to provide an overview on how to use both machine learning and traditional statistical modeling in a practical fashion. Join us on this exciting journey as we try to d explore the fascinating world of models!

>This is very much a work in progress, with more to come and plenty of things to clean up still.  If you have any feedback, we'd love to hear it. Feel free to open an issue on the repo or reach out to us directly. Thanks for reading!





## Quick Prerequisites

You'll definitely want to have some familiarity with R or Python, and some basic knowledge of statistics will be helpful. We'll try to explain things as we go, but we won't be able to cover everything. If you're looking for a good introduction to R, we recommend [R for Data Science](https://r4ds.had.co.nz/) or the [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/) for Python. Beyond that, we'll try to provide the context you need. We're not here to make you an expert, but we want you to feel comfortable with the world of models before you leave!




## About the Authors

**Michael** is a senior machine learning scientist for [Strong Analytics](https://strong.io). Prior to industry he spent his entire time in academia, earning a PhD in Experimental Psychology before turning to data science full-time as a consultant. He has a passion for helping others learn difficult stuff, and has taught a variety of statistics and data science courses at the undergraduate and graduate level, as well as workshops to people from dozens of disciplines at multiple universities, most recently at the University of Michigan. 

He also maintains a [blog](https://m-clark.github.io), and has several posts and long-form documents on a variety of data science topics there. He lives in Ann Arbor, Michigan with his wife and dog Sulu.

---

**Seth** is the Co-Director of the Master of Science in Business Analytics (MSBA) and Associate Teaching Professor at the University of Notre Dame for the IT, Analtyics, and Operations Department. He likewise has a PhD in Applied Experimental Psychology and has been teaching and consulting in data science for over 10 years. He is an excellent instructor and teaches several data science courses at the undergraduate and graduate level.  He lives in South Bend, Indiana with his wife and three kids, and spends his free time lifting more weights than he should, playing guitar, and chopping wood.



© 2024 by the authors. Web-version is CC-BY-NC-SA.