## The Foundation {-}

Intro

Key ideas
    Features, targets
    Input-output mappings
    Model Estimation
    Prediction
    Assumptions/Probabilistic outcomes/Uncertainty

Estimation
    OLS/MSE
    Maximum Likelihood (including logistic/poisson)
    Estimation as ‘Learning’
    Other Loss Functions Quick Demo

Commentary
    Opinions
    Limitations/Failure points
    Summary

### Introducing the Linear Model  (SOMETHING SNAPPIER)


Now that you have some idea of what you're getting into, it's time to dive in! In this chapter we're going to cover the building block of all modeling, and a solid understanding here will provide you the basis for the rest of what comes after, no matter how complex it gets. The **linear model** is our starting point. At first glance, it may seem like a very simple model, but it's actually quite powerful and flexible, able to take in different types of inputs, handle nonlinear relationships, temporal and spatial relations and more.  But before we start talking about the linear model, we need to talk about what a **model** is.

#### What is a Model?

At its core a model is just an **idea**. It's a way of thinking about the world, about how things work, about how things are related to each other, about how things change over time, how things are different from each other, how they are the same. The underlying thread here is that **a model expresses relationships**.  On a practical level, the model is expressed through a particular language- math, but don't let that worry you. As it's still just an idea at its core, that's the most important thing to understand about a model.  The **math is just a way of expressing the idea** in a way that can be communicated and understood by others in a standard way, helping make the idea precise.  In general, we're trying to understand how ~~A~~ relates to ~~B~~, ~~inputs~~ produce ~~outputs~~. CHANGE THESE TERMS TO examples




#### Features and Targets

In the context of a model, how we specify the nature of the relationship depends on the context. In the interest generality, we'll refer to the target as what we want to explain, and features as those aspects of the data we will use to explain it.

```{r}
#| echo: false
#| 

library(tidyverse)
library(gt)

tibble(
    feature = c('independent variable', 'predictor variable', 'explanatory variable', 'covariate', 'x', 'input')
    target = c('dependent variable', 'response', 'outcome', 'label', 'y', 'output'),
    ) %>% 
    gt() %>% 
    tab_header(
        title = "Common Terms for Features and Targets"
    )

    
```

a model is a way of expressing a relationship between a set of **features** and a **target**.  The features are the things we know, the things we can observe, the things we can measure.  The target is the thing we want to know, the thing we want to predict, the thing we want to estimate.  The features are the inputs, the target is the output.  The features are the independent variables, the target is the dependent variable.  The features are the cause, the target is the effect.  The features are the independent variables, the target is the dependent variable.  The features are the inputs, the target is the output.  The features are the cause, the target is the effect.  The features are the independent variables, the target is the dependent variable.  The features are the inputs, the target is the output.  The features are the cause, the target is the effect.  The features are the independent variables, the target is the dependent variable.  The features are the inputs, the target is the output.  The features are the cause, the target is the effect.  The features are the independent variables, the target is the dependent variable.  The features are the inputs, the target is the output.  The features are the cause, the target is the effect.  The features are the independent variables, the target is the dependent variable.  The features are the inputs, the target is the output.  The features are the cause, the target is the effect.  The features are the independent variables, the target is the dependent variable.  The features are the inputs, the target is the output.  The features are the cause, the target is the effect.  The features are the independent variables, the target is the dependent variable.
