# Other aspects of ML
## Unsupervised Learning

PCA DEMO


Traditionally **unsupervised learning** falls under dimension reduction, such that we reduce features to a smaller **latent**, or hidden, or unobserved, subset that accounts for most of the (co-)variance of the larger set, or reduce the rows to a small number of hidden, or unobserved, clusters. For example, we start with 100 features and reduce them to 10, or we classify each observation as belong to 2-3 clusters. Either way, the goal is to reduce the dimensionality of the data, not predict an explicit target.

More info about latent variables and latent linear models...

It turns out that these are the same thing, though apparently no one knows this outside of statisticians. You can discretize anything, e.g. from a nicely continuous feature to a coarse couple of categories, and this goes for latent variables as well as those we actually see in our data. For example, if I do a factor analysis with one latent feature, I can either convert it to a probability of some class with an appropriate transformation, or just say that scores higher than some cutoff are in cluster A and the others are in cluster B, and indeed, there is a whole class of clustering models called **mixture models** that do just that (i.e. estimate the latent probability of class membership). The only real difference between the two approaches is the objective (function), and for any k latent features I come up with I can create (at least) k + 1 clusters before taking into account interactions of the latent variables. 

https://stats.stackexchange.com/questions/122213/latent-class-analysis-vs-cluster-analysis-differences-in-inferences

::: {.callout-tip}
In general, do not use a dimension reduction technique as a preprocessing step for a supervised learning problem.  Instead, use a supervised learning technique that can handle high-dimensional data, has a built-in way to reduce features (e.g. lasso, boosting), or use a dimension reduction technique that is specifically designed for supervised learning (e.g. partial least squares). Creating a reduced set of features without regard to the target will generally be suboptimal for the supervised learning problem.
:::

Say something about Recommender Systems

## Reinforcement Learning

Reinforcement learning is a type of machine learning that involves training an 'agent' to make decisions in an environment. The agent learns by receiving feedback in the form of rewards or punishments for its actions. The goal of the agent is to maximize its rewards over time by learning which actions lead to positive outcomes and which lead to negative outcomes.

In reinforcement learning, the agent interacts with the environment by taking actions and receiving feedback in the form of rewards or punishments. The agent's goal is to learn a policy, which is a set of rules that dictate which actions to take in different situations. The agent learns by trial and error, adjusting its policy based on the feedback it receives from the environment.

Reinforcement learning has many applications, including robotics, game playing, and autonomous driving. It is a powerful tool for training agents to make decisions in complex environments where traditional programming approaches may not be feasible.


## Non-Tabular Data

### Image Processing

Image processing involves a range of models and techniques for analyzing images. These include image classification, object detection, image segmentation, tracking, and more. Image classification is the task of assigning a label to an image. Object detection is the task of identifying the location of objects in an image. Image segmentation is the task of identifying the boundaries of objects in an image. Tracking is the task of following objects over time.

In general, your base data is an image, which is represented as a matrix of pixel values. For example, each row of the matrix could be a grayscale value for a pixel, or it could be a vector of RGB values for a pixel, such that each row is an image, the matrix is a collection of images, while the third dimension is the color channel of red, green and blue.

The modeling goal then is to extract features from the image that can be used for the task at hand. For example, you might extract features such as color, texture, and shape. You can then use these features to train a model to classify images or whatever your task may be.

Image processing is a broad field with many applications. It is used in medical imaging, satellite imagery, self-driving cars, and more. And while it can be really fun to classify objects such as cats and dogs, or generate images from text and vice versa, it can be quite challenging due to the size of the data, issues specific to video/image quality, and the model complexity.  Even if your base data is often the same or very similar, the model architecture and training process can vary widely depending on the task at hand.



### Natural Language Processing

Natural language processing (NLP) is a field of study that focuses on the interaction between computers and human language. It is a subfield of artificial intelligence and linguistics. NLP is used in a wide range of applications, including machine translation, speech recognition, text classification, and more. NLP is behind some of the most exciting applications today, such as ChatGPT, which continues to amaze with its capabities of generating summaries of articles, answering questions, and even writing code.

Nowadays one can simply use a pretrained model for most NLP tasks, and much of the trouble comes with generating the best prompt to produce the desired results.  Simply feeding a lot of text to the model will often not produce an optimal product. However, the field and the models are evolving extremely rapidly, and things are getting easier all the time.

### Artificial Intelligence

The prospect of combining models for computer vision, natural language processing, audio processing, and other domains can produce tools that mimic many aspects of what we call intelligence[^intel]. Current approaches can pass law and medical exams, create better explanations of images and text, and produce conversation on par with humans.  AI even helped to create this book!

[^intel]: It seems most discussions of AI in the public sphere never bother to mention how they would define intelligence in the first place, and academics have struggled with the concept for centuries.

From a modeling aspect, [many put ML as a subset of AI](https://azure.microsoft.com/en-us/resources/cloud-computing-dictionary/artificial-intelligence-vs-machine-learning), but this is a bit off the mark from a modeling perspective in our opinion. For example, model-wise, any aspect of what we'd call modern AI only employs deep learning models (although it didn't in the past), while the ML approach to training and evaluating models can be used for any underlying model from simple linear models to the most complex deep learning models, whether the application falls under the heading of AI or not. Furthemore, statistical model applications have never seriously attempted what we might call AI.  If AI is some 'autonomous and general tools that attempt to engage the world in a human-like way or better', it's not clear why it'd be compared to ML in the first place. It's like saying the brain is a subset of cognition. The brain does the work, much like ML, and gives rise to what we call cognition, but generally we would not compare the brain to cognition. 

Many of the non-AI settings we use modeling for may well be things we can eventually rely on AI to do, but the computational limits, whether the amount of data that would be required for AI models to be better than others, or the ability of AI to be able to deal with situations in which there is *only* small bits of data, are still hinderances in application. However, it's likely these will eventually be overcome.


DL models and ML in general can be used for non-AI settings, and the models still employ the *perspective* of the ML approach - i.e. they are still trained on data, and the model is still a function of the data. Furthermore, ML is not a set of models, but a general approach to modeling, so it's not clear how it is a subset of AI. One aspect of AI is that the models are very complex and trained on a great deal more data than typical ML settings.



**Artificial general intelligence (AGI)** is the holy grail of AI, and but is not consistently defined. In general, the idea behind AGI is the creation of some autonomous agent that can perform any task that a human can perform, many that humans cannot, and generalize abilities to new problems that have not even been seen yet. It seems we are getting closer to AGI all the time, but it's not yet clear when it will be achieved, or even what it will look like when it is achieved.




The future is here, and it is amazing.

