
# References

---
nocite: |
  @agresti_foundations_2015, @albon_machine_2024, @albon_machine_nodate, @amazon_what_nodate, @andrej_karpathy_lets_2024, @arel-bundock_marginal_2024, @bai_understanding_2021, @barrett_causal_2023, @belkin_reconciling_2019, @biecek_explanatory_2020, @bischl_applied_2024, @bishop_pattern_2006, @boykis_what_2023, @brownlee_gentle_2016, @brownlee_gentle_2019, @brownlee_gradient_2021, @brownlee_how_2020, @burges_learning_2005, @burges_ranknet_nodate, @bycroft_llm_2023, @carpenter_prior_2023, @causalml_causalml_2023, @cawley_over-fitting_2010, @chawla_smote_2002, @chernozhukov_applied_2024, @clark_bayesian_2022, @clark_deep_2022, @clark_generalized_2022, @clark_graphical_2018, @clark_mixed_2023, @clark_practical_2020, @clark_this_2021, @cohen_statistical_2009, @cross_validated_answer_2020, @cunningham_causal_2023, @dahabreh_causal_2024, @databricks_what_2019, @davison_bootstrap_1997, @dobson_introduction_2018, @dunn_generalized_2018, @efron_introduction_1994, @facure_alves_causal_2022, @fahrmeir_regression_2013, @faraway_linear_2014, @ferrari_beta_2004, @fleuret_little_2023, @fortuner_machine_2023, @fox_applied_2015, @gelman_advanced_2024, @gelman_bayesian_2013, @gelman_data_2006, @gelman_regression_2020, @gelman_what_2013, @goodfellow_deep_2016, @google_classification_2024, @google_imbalanced_nodate, @google_introduction_2023, @google_machine_2023, @google_reducing_2024, @google_what_nodate, @greene_econometric_2017, @grolemund_welcome_2023, @hardin_generalized_2018, @harrell_regression_2015, @hastie_elements_2017, @heiss_marginalia_2022, @hernan_c-word_2018, @howard_practical_2024, @hugging_face_byte-pair_nodate, @hvitfeldt_feature_2024, @hyndman_forecasting_2021, @james_introduction_2021, @jiang_visual_2020, @koenker_galton_2000, @koenker_quantile_2005, @kruschke_doing_2010, @kuhn_applied_2023, @kuhn_tidy_2023, @kunzel_metalearners_2019, @lang_mlr3_2019, @lee_deep_2017, @lones_how_2024, @mahr_random_2021, @masis_interpretable_2023, @mccullagh_generalized_2019, @mcculloch_logical_1943, @mcelreath_statistical_2020, @mckinney_python_2023, @microsoft_generative_nodate, @molnar_interpretable_2023, @monroe_imbalanced_2024, @morgan_counterfactuals_2014, @murphy_machine_2012, @murphy_probabilistic_2023, @navarro_learning_2018, @nelder_generalized_1972, @niculescu-mizil_predicting_2005, @pearl_causal_2009, @pearl_causal_2022, @peng_r_nodate, @penn_state_54_2018, @pok_how_2020, @quantmetry_mapie_2024, @raschka_about_2014, @raschka_build_2023, @raschka_machine_2022, @raschka_machine_2023, @rasmussen_gaussian_2005, @ripley_pattern_1996, @roback_beyond_2021, @roberts_neural_nodate, @rocca_handling_2019, @rovine_peirce_2004, @schmidhuber_annotated_2022, @scikit-learn_116_2023, @scikit-learn_nested_2023, @sen_decoder-only_nodate, @shevchenko_types_2023, @shorten_text_2021, @simpson_using_2021, @stackexchange_are_2015, @statquest_with_josh_starmer_bootstrapping_2021, @statquest_with_josh_starmer_gradient_2019, @statquest_with_josh_starmer_stochastic_2019, @turrell_python_2024, @ucla_advanced_research_computing_faq_2023, @ucla_advanced_research_computing_faq_nodate, @vanderplas_python_2016, @vaswani_attention_2017, @walker_analyzing_2023, @weed_learning_2021, @welchowski_techniques_2022, @wikipedia_cross-entropy_2024, @wikipedia_exponential_2024, @wikipedia_gradient_2024, @wikipedia_relationships_2023, @wood_generalized_2017, @wooldridge_introductory_2012, @zhang_dive_2023
---

::: {#refs}
:::


```{r include=FALSE}
#| eval: false
#| echo: false
# generate a BibTeX database automatically for some R packages
knitr::write_bib(c(
    .packages(), "mlr3", "mgcv", "xgboost", 'lightgbm', 'glmnet'
), "packages.bib")
```

