<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.339">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Models Demystified - 6&nbsp; Extending the Linear Model</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./machine_learning.html" rel="next">
<link href="./generalized_linear_models.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./linear_models.html">Linear Models</a></li><li class="breadcrumb-item"><a href="./linear_model_extensions.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Extending the Linear Model</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Models Demystified</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/m-clark/book-of-models" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Models-Demystified.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Linear Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linear_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Foundation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_criticism.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Knowing Your Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">How Did We Get Here?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./generalized_linear_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Generalized Linear Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linear_model_extensions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Extending the Linear Model</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Machine Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./machine_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Core Concepts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ml_common_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Common Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ml_more.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">More ML</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Other Considerations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Data Issues in Modeling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Causal Modeling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./misc_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Misc Models</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dataset_descriptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Dataset Descriptions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./matrix_operations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Matrix Operations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_placeholder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Other to come</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#sec-lm-extend-key-ideas" id="toc-sec-lm-extend-key-ideas" class="nav-link active" data-scroll-target="#sec-lm-extend-key-ideas"><span class="header-section-number">6.1</span> Key Ideas</a>
  <ul class="collapse">
  <li><a href="#sec-lm-extend-why" id="toc-sec-lm-extend-why" class="nav-link" data-scroll-target="#sec-lm-extend-why"><span class="header-section-number">6.1.1</span> Why this matters?</a></li>
  <li><a href="#sec-lm-extend-good" id="toc-sec-lm-extend-good" class="nav-link" data-scroll-target="#sec-lm-extend-good"><span class="header-section-number">6.1.2</span> Good to know</a></li>
  </ul></li>
  <li><a href="#sec-lm-extend-quantile" id="toc-sec-lm-extend-quantile" class="nav-link" data-scroll-target="#sec-lm-extend-quantile"><span class="header-section-number">6.2</span> Quantile Regression</a>
  <ul class="collapse">
  <li><a href="#sec-quantile-why" id="toc-sec-quantile-why" class="nav-link" data-scroll-target="#sec-quantile-why"><span class="header-section-number">6.2.1</span> Why Should You Care?</a></li>
  <li><a href="#sec-quantile-break" id="toc-sec-quantile-break" class="nav-link" data-scroll-target="#sec-quantile-break"><span class="header-section-number">6.2.2</span> When The Mean Breaks Down</a></li>
  <li><a href="#sec-quantile-data" id="toc-sec-quantile-data" class="nav-link" data-scroll-target="#sec-quantile-data"><span class="header-section-number">6.2.3</span> Data Import and Preparation</a></li>
  <li><a href="#sec-quantile-standard" id="toc-sec-quantile-standard" class="nav-link" data-scroll-target="#sec-quantile-standard"><span class="header-section-number">6.2.4</span> Standard Functions</a></li>
  <li><a href="#sec-quantile-loss" id="toc-sec-quantile-loss" class="nav-link" data-scroll-target="#sec-quantile-loss"><span class="header-section-number">6.2.5</span> Quantile Loss Function</a></li>
  <li><a href="#sec-quantile-model" id="toc-sec-quantile-model" class="nav-link" data-scroll-target="#sec-quantile-model"><span class="header-section-number">6.2.6</span> Model Fitting</a></li>
  </ul></li>
  <li><a href="#sec-gam" id="toc-sec-gam" class="nav-link" data-scroll-target="#sec-gam"><span class="header-section-number">6.3</span> Additive Models</a>
  <ul class="collapse">
  <li><a href="#sec-gam-why" id="toc-sec-gam-why" class="nav-link" data-scroll-target="#sec-gam-why"><span class="header-section-number">6.3.1</span> Why Should You Care?</a></li>
  <li><a href="#sec-gam-curve" id="toc-sec-gam-curve" class="nav-link" data-scroll-target="#sec-gam-curve"><span class="header-section-number">6.3.2</span> When Straight Lines Aren’t Enough</a></li>
  <li><a href="#sec-gam-standard" id="toc-sec-gam-standard" class="nav-link" data-scroll-target="#sec-gam-standard"><span class="header-section-number">6.3.3</span> Standard Functions</a></li>
  <li><a href="#sec-gam-splines" id="toc-sec-gam-splines" class="nav-link" data-scroll-target="#sec-gam-splines"><span class="header-section-number">6.3.4</span> Splines</a></li>
  <li><a href="#sec-gam-model-matrix" id="toc-sec-gam-model-matrix" class="nav-link" data-scroll-target="#sec-gam-model-matrix"><span class="header-section-number">6.3.5</span> Model Matrix Function</a></li>
  <li><a href="#sec-gam-model-matrix" id="toc-sec-gam-model-matrix" class="nav-link" data-scroll-target="#sec-gam-model-matrix"><span class="header-section-number">6.3.6</span> Model Matrix</a></li>
  <li><a href="#sec-gam-model-fitting" id="toc-sec-gam-model-fitting" class="nav-link" data-scroll-target="#sec-gam-model-fitting"><span class="header-section-number">6.3.7</span> Model Fitting</a></li>
  <li><a href="#prediction" id="toc-prediction" class="nav-link" data-scroll-target="#prediction"><span class="header-section-number">6.3.8</span> Prediction</a></li>
  <li><a href="#sec-gam-penalty" id="toc-sec-gam-penalty" class="nav-link" data-scroll-target="#sec-gam-penalty"><span class="header-section-number">6.3.9</span> Penalized Cubic Spline</a></li>
  <li><a href="#sec-gam-penalty-model" id="toc-sec-gam-penalty-model" class="nav-link" data-scroll-target="#sec-gam-penalty-model"><span class="header-section-number">6.3.10</span> Penalized Model Fitting Function</a></li>
  <li><a href="#sec-gam-penalty-fitting" id="toc-sec-gam-penalty-fitting" class="nav-link" data-scroll-target="#sec-gam-penalty-fitting"><span class="header-section-number">6.3.11</span> Penalized Model Fitting</a></li>
  </ul></li>
  <li><a href="#sec-mixed-models" id="toc-sec-mixed-models" class="nav-link" data-scroll-target="#sec-mixed-models"><span class="header-section-number">6.4</span> Mixed Models</a>
  <ul class="collapse">
  <li><a href="#sec-mixed-models-why" id="toc-sec-mixed-models-why" class="nav-link" data-scroll-target="#sec-mixed-models-why"><span class="header-section-number">6.4.1</span> Why Should You Care?</a></li>
  <li><a href="#sec-mixed-models-knowing" id="toc-sec-mixed-models-knowing" class="nav-link" data-scroll-target="#sec-mixed-models-knowing"><span class="header-section-number">6.4.2</span> Knowing Your Data</a></li>
  <li><a href="#sec-mixed-models-standard" id="toc-sec-mixed-models-standard" class="nav-link" data-scroll-target="#sec-mixed-models-standard"><span class="header-section-number">6.4.3</span> Standard Functions</a></li>
  <li><a href="#model-matrix" id="toc-model-matrix" class="nav-link" data-scroll-target="#model-matrix"><span class="header-section-number">6.4.4</span> Model Matrix</a></li>
  <li><a href="#likelihood-function" id="toc-likelihood-function" class="nav-link" data-scroll-target="#likelihood-function"><span class="header-section-number">6.4.5</span> Likelihood Function</a></li>
  <li><a href="#model-fitting" id="toc-model-fitting" class="nav-link" data-scroll-target="#model-fitting"><span class="header-section-number">6.4.6</span> Model Fitting</a></li>
  </ul></li>
  <li><a href="#performance-comparisons" id="toc-performance-comparisons" class="nav-link" data-scroll-target="#performance-comparisons"><span class="header-section-number">6.5</span> Performance Comparisons</a></li>
  <li><a href="#sec-lm-extend-wrap" id="toc-sec-lm-extend-wrap" class="nav-link" data-scroll-target="#sec-lm-extend-wrap"><span class="header-section-number">6.6</span> Wrapping Up</a></li>
  <li><a href="#sec-lm-extend-next-steps" id="toc-sec-lm-extend-next-steps" class="nav-link" data-scroll-target="#sec-lm-extend-next-steps"><span class="header-section-number">6.7</span> Next Steps</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/m-clark/book-of-models/edit/main/linear_model_extensions.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./linear_models.html">Linear Models</a></li><li class="breadcrumb-item"><a href="./linear_model_extensions.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Extending the Linear Model</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-lm-extend" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Extending the Linear Model</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>

<p>With thin linear model and generalized linear models, we have a solid foundation for modeling. We’ve seen how there is a notable amount we can do with a conceptually simple approach. We’ve also seen how we can extend the linear model to handle different types of data to help us understand and make some inferences about the relationships between our features and target.</p>
<p>In this chapter, we want to show you how to extend the linear model even further with still common tools. These particular methods are also good examples of how we can think about our data and approach in different ways, and can serve as a good starting point for even more techiques you may want to explore in the future.</p>
<section id="sec-lm-extend-key-ideas" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="sec-lm-extend-key-ideas"><span class="header-section-number">6.1</span> Key Ideas</h2>
<ul>
<li>The linear and generalized linear models are great and powerful starting points for modeling, but they are not the only options. But it’s good to know a few more ways we can extend the approach.</li>
<li>Quantile regression, GAMs, and mixed models allow us to model relationships that are not linear or monotonic, and can help us to better understand our data.</li>
<li>While these seem like very different approaches, we can still use our linear model concepts and approach at the core, take similar estimation steps, and even have similar, albeit more, interpretation.</li>
</ul>
<section id="sec-lm-extend-why" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="sec-lm-extend-why"><span class="header-section-number">6.1.1</span> Why this matters?</h3>
<p>The linear model is a great starting point for modeling. It is a simple approach that can be used to model a wide variety of relationships between features and targets. It is also a great way to get a feel for how to think about modeling. But linear and generalized models are just the starting point, and the models depicted here are very common extensions used in a variety of disciplines and industries.</p>
</section>
<section id="sec-lm-extend-good" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="sec-lm-extend-good"><span class="header-section-number">6.1.2</span> Good to know</h3>
<p>While these models are extensions of the linear model, they are not necessarily more complex. They are also not necessarily more difficult to interpret. However, you likely want to be fairly comfortable with standard linear models at least before you start to explore these extensions.</p>
</section>
</section>
<section id="sec-lm-extend-quantile" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="sec-lm-extend-quantile"><span class="header-section-number">6.2</span> Quantile Regression</h2>
<blockquote class="blockquote">
<p>Oh, you think the mean is your ally. But you merely adopted the mean; I was born in it, molded by it. I didn’t see anything interesting until I was already a man. And by then, it was nothing to me but illuminating. – Bane (probably)</p>
</blockquote>
<p>People generally understand the concept of the arithmetic mean. You see it some time during elementary school, it gets tossed around in daily language (usually using the word “average”), and it is statistically important. After all, where would the normal distribution be without a mean? Why, though, do we feel so tied to it from a regression modeling perspective? Yes, it has handy features, but it is also a bit restrictive to the types of relationships that it can actually model well.</p>
<p>In this chapter, we want to show you what to do when the mean betrays you – and trust us, the mean will betray you at some point!</p>
<section id="sec-quantile-why" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="sec-quantile-why"><span class="header-section-number">6.2.1</span> Why Should You Care?</h3>
<p>Sometimes the mean doesn’t make as much sense to focus on for summarizing our data, whether due to extreme scores that have too much influence, or you’re interested at how your model is performing in different parts of your data, such as the top 10%, quantile regression can be helpful. Quantile regression will give you the ability to model the relationship between your features and target at different quantiles of your target, with the median being a starting point. Maybe people who are older are more likely to rate movies higher, but that relationship is stronger for people who rate movies higher than the median. Quantile regression will let you model that relationship.</p>
</section>
<section id="sec-quantile-break" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="sec-quantile-break"><span class="header-section-number">6.2.2</span> When The Mean Breaks Down</h3>
<p>In a perfect data world, we like to assume the mean is equal to the middle observation of the data: the <em>median</em>. But that is only when things are symmetric though, and usually our data comes loaded with challenges. Skewness and even just a few extreme scores in your data may cause a rift between the median and the mean.</p>
<p>Let’s say we take the integers between 1 and 10, and find the mean.</p>
<p><span class="math display">\[\frac{1+2+3+4+5+6+7+8+9+10}{10} =  5.5\]</span></p>
<p>The middle value in that vector of numbers would also be 5.5.</p>
<p>What happens we replace the 1 with a more extreme value, like -10?</p>
<p><span class="math display">\[\frac{-10+2+3+4+5+6+7+8+9+10}{10} =  4.5\]</span></p>
<p>With just one dramatic change, our mean went down by a whole point. The median observation, though, is still 5.5. In short, the median is invariant to wild swings out in the tails of your numbers.</p>
<p>You might be saying to yourself, “Why should I care about this central tendency chicanery?” Let us tell you why you should care – the least squares approach to the standard linear model dictates that the regression line needs to be fit through the means of the variables. If you have extreme scores that influence the mean, then your regression line will also be influenced by those extreme scores.</p>
<p>Let’s look at a few different regression lines:</p>
<div class="cell" data-tbl-cap="Linear line without extreme scores">
<div class="cell-output-display">
<p><img src="linear_model_extensions_files/figure-html/linear_line_no_extremes-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now, what would happen if we replaced a few of our observations with extreme scores?</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linear_model_extensions_files/figure-html/linear_line_extremes-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Linear line with extreme scores</figcaption>
</figure>
</div>
</div>
</div>
<p>With just a casual glance, it doesn’t look like our two regression lines are that different. They both look like they have a similar positive slope, so all should be good. To offer a bit more clarity, though, let’s put those lines in the same space:</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linear_model_extensions_files/figure-html/both_linear_lines-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Line lines with and without extreme scores</figcaption>
</figure>
</div>
</div>
</div>
<p>With 1000 observations, we see that having just 10 extreme scores is enough to change the regression line, even if just a little. But that little bit can mean a huge difference for predictions or just the conclusions we come to.</p>
<p>There are a few approaches we could take here, with common approaches being dropping those observations or Windsorizing them. Throwing away data because you don’t like the way it behaves is nearing on statistical abuse and Windsorization is just replacing those extreme values with numbers that you like a little bit better. Let’s not do that!</p>
<p>A better answer to this challenge might be to not fit the regression line through the mean, but the median instead. This is where quantile regression becomes handy. Formally, this model can be expressed as:</p>
<p><span class="math display">\[
Q_{Y\vert X}(\tau) = X\beta_\tau
\]</span></p>
<p>Where we can find the estimation of <span class="math inline">\(\beta_\tau\)</span> as:</p>
<p>TODO: change a bit to other loss function depiction, add the explicit quantile function</p>
<p><span class="math display">\[
\hat\beta_\tau = \arg \min_{\beta \in \mathbb{R}^k} \sum_{i-1}^n(\rho_\tau(Y_i-X_i\beta))
\]</span></p>
<p><span class="math display">\[
=\underset{q\in \mathbb{R}}{\mbox{arg min}}  \left[(\tau - 1)\sum_{y_{i}&lt;q}(y_{i}-q)+\tau\sum_{y_{i}\geq q}(y_{i}-q) \right]
\]</span></p>
<p>With quantile regression, we are given an extra parameter for the model: <span class="math inline">\(\tau\)</span> or <em>tau</em>. The tau parameter let’s us choose which quantile we want to use for our line fitting. Since the median splits the data in half, we can translate that to a quantile of .5.</p>
</section>
<section id="sec-quantile-data" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="sec-quantile-data"><span class="header-section-number">6.2.3</span> Data Import and Preparation</h3>
<p>Let’s bring in our movie reviews data. Let’s say that we are curious about the relationship between the <code>total_reviews</code> variable and the <code>rating</code> variable. First, we need to get our data ready for our home-brewed functions.</p>
<p>TODO: Rescale total_reviews or use the scaled version</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>reviews <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"data/movie_reviews_processed.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>reviews <span class="ot">=</span> <span class="fu">na.omit</span>(reviews)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>X <span class="ot">=</span> reviews<span class="sc">$</span>total_reviews</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>X <span class="ot">=</span> <span class="fu">cbind</span>(<span class="dv">1</span>, X)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>y <span class="ot">=</span> reviews<span class="sc">$</span>rating</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>reviews <span class="op">=</span> pd.read_csv(<span class="st">"data/movie_reviews_processed.csv"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>reviews <span class="op">=</span> reviews.dropna()</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> pd.DataFrame(</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  {<span class="st">'intercept'</span>: <span class="dv">1</span>, </span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">'total_reviews'</span>: reviews[<span class="st">'total_reviews'</span>]}</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> reviews[<span class="st">'rating'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-quantile-standard" class="level3" data-number="6.2.4">
<h3 data-number="6.2.4" class="anchored" data-anchor-id="sec-quantile-standard"><span class="header-section-number">6.2.4</span> Standard Functions</h3>
<p>We can see how we can use <code>quantreg</code> and <code>statsmodels</code> to create a quantile regression. For both, we will start with a median regression; in other words, a quantile of .5.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quantreg)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>median_test <span class="ot">=</span> <span class="fu">rq</span>(rating <span class="sc">~</span> total_reviews, <span class="at">tau =</span> .<span class="dv">5</span>, </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> reviews)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(median_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call: rq(formula = rating ~ total_reviews, tau = 0.5, data = reviews)

tau: [1] 0.5

Coefficients:
              coefficients lower bd upper bd
(Intercept)   2.70278      2.53409  2.77655 
total_reviews 0.00007      0.00006  0.00010 </code></pre>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>median_test <span class="op">=</span> smf.quantreg(<span class="st">'rating ~ total_reviews'</span>, </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                           data <span class="op">=</span> reviews).fit(q <span class="op">=</span> <span class="fl">.5</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>                           </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>median_test.summary()                           </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>QuantReg Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>rating</td>
<td data-quarto-table-cell-role="th">Pseudo R-squared:</td>
<td>0.05241</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>QuantReg</td>
<td data-quarto-table-cell-role="th">Bandwidth:</td>
<td>0.3092</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>Least Squares</td>
<td data-quarto-table-cell-role="th">Sparsity:</td>
<td>1.645</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Sun, 17 Dec 2023</td>
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>1000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>20:09:34</td>
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>998</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th"></td>
<td></td>
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>1</td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">t</td>
<td data-quarto-table-cell-role="th">P&gt;|t|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Intercept</td>
<td>2.6929</td>
<td>0.052</td>
<td>51.706</td>
<td>0.000</td>
<td>2.591</td>
<td>2.795</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">total_reviews</td>
<td>7.361e-05</td>
<td>9.17e-06</td>
<td>8.029</td>
<td>0.000</td>
<td>5.56e-05</td>
<td>9.16e-05</td>
</tr>
</tbody>
</table>
<br><br>The condition number is large, 1.14e+04. This might indicate that there are<br>strong multicollinearity or other numerical problems.
</div>
</div>
</div>
</div>
</div>
<p>Fortunately, our interpretation of this result isn’t all that different from a standard linear model – the rating should increase by .00007 for every additional review. However, this is at rating median, not the mean, like the standard linear model.</p>
<p>Quantile regression is not a one-trick-pony. Remember, it is called quantile regression – not median regression. Being able to compute a median regression is just the default. What we can do also is to model different quantiles of the same data. It gives us the ability to answer brand new questions – does the relationship between user age and their ratings change at different quantiles of rating? Very cool!</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linear_model_extensions_files/figure-html/quantile_lines-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Quantile regression lines</figcaption>
</figure>
</div>
</div>
</div>
<p>Instead of a single model to capture the trend through the mean of the data, we can now examine the trends within 5 different quantiles of the data (we aren’t limited to just those quantiles, though, and you can examine any of them that you might find interesting). If we had to put some words to our visualization, we could say that all of the quantiles show a positive relationship. While they all appear to have roughly the same slope, it appears that the 90th quantile has a slightly steeper slope than the other quantiles, if only modestly so.</p>
<p>TODO: MOVE TO ESTIMATION OR ONLINE ONLY</p>
</section>
<section id="sec-quantile-loss" class="level3" data-number="6.2.5">
<h3 data-number="6.2.5" class="anchored" data-anchor-id="sec-quantile-loss"><span class="header-section-number">6.2.5</span> Quantile Loss Function</h3>
<p>Now that we know how to use standard functions for quantile regression, let’s see one way that we can create a least squares loss function for fitting a linear regression model and compare it with a function for quantile loss.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>least_squares_loss <span class="ot">=</span> <span class="cf">function</span>(par, X, y) {</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  linear_parameters <span class="ot">=</span> X <span class="sc">%*%</span> par</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  mu <span class="ot">=</span> linear_parameters   </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  loss <span class="ot">=</span> <span class="fu">crossprod</span>(y <span class="sc">-</span> mu)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>quantile_loss <span class="ot">=</span> <span class="cf">function</span>(par, X, y, tau) {</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  linear_parameters <span class="ot">=</span> X <span class="sc">%*%</span> par</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  residual <span class="ot">=</span> y <span class="sc">-</span> linear_parameters</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  loss <span class="ot">=</span> <span class="fu">ifelse</span>(</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    residual <span class="sc">&lt;</span> <span class="dv">0</span> , </span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    (<span class="sc">-</span><span class="dv">1</span> <span class="sc">+</span> tau)<span class="sc">*</span>residual, </span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    tau<span class="sc">*</span>residual</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(loss)</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> least_squares_loss(par, X, y):</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  linear_parameters <span class="op">=</span> X.dot(par)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  mu <span class="op">=</span> linear_parameters</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  loss <span class="op">=</span> np.dot(y <span class="op">-</span> mu, y <span class="op">-</span> mu)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> loss</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> quantile_loss(par, X, y, tau):</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  linear_parameters <span class="op">=</span> X.dot(par)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  residual <span class="op">=</span> y <span class="op">-</span> linear_parameters</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  loss <span class="op">=</span> []</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> i <span class="kw">in</span> residual:</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> i <span class="op">&lt;</span> <span class="dv">0</span>: loss.append((<span class="op">-</span><span class="dv">1</span> <span class="op">+</span> tau)<span class="op">*</span>i)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>: loss.append(tau<span class="op">*</span>i)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> <span class="bu">sum</span>(loss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>You’ll notice right away that we have a few differences. Our quantile loss function includes the <strong>tau</strong> argument, which will let us set our quantile of interest; naturally, it can be any value between 0 and 1. The residual is multiplied by the tau value, only if the residual is greater than 0. If the residual is negative, we need to add tau to -1. Since we need a positive value for our loss values, we will multiply our negative residuals by the negative value produced from -1 plus our tau value. After that, we just sum all of those positive loss values and do our best to minimize that summed value.</p>
</section>
<section id="sec-quantile-model" class="level3" data-number="6.2.6">
<h3 data-number="6.2.6" class="anchored" data-anchor-id="sec-quantile-model"><span class="header-section-number">6.2.6</span> Model Fitting</h3>
<p>Now that we have our data and our loss function, we can fit the model almost exactly like our standard linear model. Again, note the difference here with our tau value, which we’ve set to .5 to represent the median.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">optim</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">par =</span> <span class="fu">c</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">total_reviews =</span> <span class="dv">0</span>),</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">fn  =</span> quantile_loss,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">X   =</span> X,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">y   =</span> y,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">tau =</span> .<span class="dv">5</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>)<span class="sc">$</span>par</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    intercept total_reviews 
 2.702730e+00  7.258694e-05 </code></pre>
</div>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> minimize</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>minimize(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  quantile_loss, </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  x0 <span class="op">=</span> np.array([<span class="dv">0</span>, <span class="dv">0</span>]), </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  args <span class="op">=</span> (X, y, <span class="fl">.5</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  ).x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>array([2.70270449e+00, 7.26658864e-05])</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="sec-gam" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="sec-gam"><span class="header-section-number">6.3</span> Additive Models</h2>
<blockquote class="blockquote">
<p>Wiggle, wiggle, wiggle, yeah! – LMFAO</p>
</blockquote>
<p>TODO: GAM gets a bit deep, but we do want to keep discussion of penalized appoach, and ultimately a word on the random effect connection.</p>
<section id="sec-gam-why" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="sec-gam-why"><span class="header-section-number">6.3.1</span> Why Should You Care?</h3>
<p>Not every relationship is linear and not every relationship is monotonic. Sometimes, you need to be able to model a relationship that has a fair amount of nonlinearity – they can appear as slight curves, waves, and any other type of wiggle that you can imagine. Additive models will give you the ability to model those nonlinear relationships between your features and target.</p>
</section>
<section id="sec-gam-curve" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="sec-gam-curve"><span class="header-section-number">6.3.2</span> When Straight Lines Aren’t Enough</h3>
<p>Fitting a line through your data is always going to be useful, regardless of whether you are using the median or the mean. Those lines give us a wonderful ability to say important things about the relationships between variables and how one variable might influence another. What if we just want to dispense with the notion that we need to fit a straight line through some mass of the data? What if we relax the idea that we need a straight line and think in terms of fitting something curvy through the data.</p>
<p>In other words, we can go from the straight line in <a href="#fig-regular_linear_line" class="quarto-xref">Figure&nbsp;<span>6.1</span></a>:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-regular_linear_line" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="linear_model_extensions_files/figure-html/fig-regular_linear_line-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;6.1: A standard linear model</figcaption>
</figure>
</div>
</div>
</div>
<p>TODO: there is actually a poly effect for length in minutes, but it may not</p>
<p>To the curve seen here:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-gam_model_line" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="linear_model_extensions_files/figure-html/fig-gam_model_line-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;6.2: A generalized additive model</figcaption>
</figure>
</div>
</div>
</div>
<p>That curved line in <a href="#fig-gam_model_line" class="quarto-xref">Figure&nbsp;<span>6.2</span></a> is called a spline. Oddly enough, we can still use a linear model to fit this spline through the data. While this might not give us the same tidy explanation that a typical line would offer, we will certainly get better prediction.</p>
<p>These models belong to a broad group of <em>generalized additive models</em>, often shortened to GAMs. When we fit a quantile regression, we made a slight tweak to the <em>y</em>; to fit a GAM, we are going to tweak our predictors. How are we going to tweak them, you might ask? We are essentially going to let them be an <em>additive</em> function of features. We will have a model that looks like this:</p>
<p><span class="math display">\[
y = f(x) + \epsilon
\]</span></p>
<p>This isn’t much different than before, and technically, it really isn’t. It’s the same linear combination of features we have with a basic linear model. The difference is that we are going to let <span class="math inline">\(f(x)\)</span> be a function of <span class="math inline">\(x\)</span> that allows us to capture other types of relationships by expanding the feature <span class="math inline">\(x\)</span> in different ways, some that can be complex, but on the practical side are just extra columns in the <strong>model matrix</strong>. If you are familiar with polynomial regression, you can think of this as a generalization of that approach, but which is identical in spirit<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<p>These additive features will allow us to capture nonlinearities in our data very nicely. At this point, you might be asking yourself, “Why couldn’t I just use some type of polynomial regression or even a nonlinear regression?”. Of course you could, but both have limitations. The typical polynomial regression tends to overfit the data you currently have, and <strong>you</strong> are forcing curves to fit through the data. To use a nonlinear model, you need to know what the underlying nonlinear form actually looks like before you can even specify the model, and without extra steps, will also tend to overfit. A GAM handles this situation a little better in that it will produce a curve that will best fit through the data, without the need to know the underlying functional form.</p>
</section>
<section id="sec-gam-standard" class="level3" data-number="6.3.3">
<h3 data-number="6.3.3" class="anchored" data-anchor-id="sec-gam-standard"><span class="header-section-number">6.3.3</span> Standard Functions</h3>
<p>Now that you have some background, let’s . In most respects, we can use the same sort of approach as we did with our other model examples.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<p>We’ll use the very powerful <code>mgcv</code> package in R. The <code>s</code> function will allow us to use a spline approach to capture the nonlinearity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mgcv)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>gam_model <span class="ot">=</span> <span class="fu">gam</span>(rating <span class="sc">~</span> <span class="fu">s</span>(total_reviews_sc, <span class="at">bs =</span> <span class="st">"cr"</span>), <span class="at">data =</span> reviews)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gam_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Family: gaussian 
Link function: identity 

Formula:
rating ~ s(total_reviews_sc, bs = "cr")

Parametric coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.05140    0.01862   163.9   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Approximate significance of smooth terms:
                      edf Ref.df    F p-value    
s(total_reviews_sc) 8.672  8.966 16.2  &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-sq.(adj) =  0.124   Deviance explained = 13.1%
GCV = 0.34994  Scale est. = 0.34655   n = 1000</code></pre>
</div>
</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<p>We use the <code>pygam</code> package in Python to fit a GAM. It’s very much in the spirit of R’s <code>mgcv</code>. The <code>s</code> function will allow us to use a spline approach to capture the nonlinearity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pygam <span class="im">import</span> LinearGAM, s</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> reviews[<span class="st">'rating'</span>]</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> pd.DataFrame({<span class="st">'total_reviews_sc'</span>: reviews[<span class="st">'total_reviews_sc'</span>]})</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>gam_model <span class="op">=</span> LinearGAM(s(<span class="dv">0</span>, n_splines<span class="op">=</span><span class="dv">10</span>)).fit(X, y)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>gam_model.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>LinearGAM                                                                                                 
=============================================== ==========================================================
Distribution:                        NormalDist Effective DoF:                                      7.3297
Link Function:                     IdentityLink Log Likelihood:                                 -1286.4909
Number of Samples:                         1000 AIC:                                             2589.6412
                                                AICc:                                            2589.7981
                                                GCV:                                                0.3553
                                                Scale:                                              0.3506
                                                Pseudo R-Squared:                                    0.119
==========================================================================================================
Feature Function                  Lambda               Rank         EDoF         P &gt; x        Sig. Code   
================================= ==================== ============ ============ ============ ============
s(0)                              [0.6]                10           7.3          1.11e-16     ***         
intercept                                              1            0.0          1.11e-16     ***         
==========================================================================================================
Significance codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

WARNING: Fitting splines and a linear function to a feature introduces a model identifiability problem
         which can cause p-values to appear significant when they are not.

WARNING: p-values calculated in this manner behave correctly for un-penalized models or models with
         known smoothing parameters, but when smoothing parameters have been estimated, the p-values
         are typically lower than they should be, meaning that the tests reject the null too readily.</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>For the results of our gam model, one of the best places to look first is the <code>edf</code>/<code>EDoF</code> column. This column indicates the <em>effective degrees of freedom</em>. You can think of it as a measure of wiggle in the relationship between the predictor and the target. The higher the value, the more wiggle you have. If you have a value close to 1, then you have a linear relationship. With our current result, we can be pretty confident that a nonlinear relationship gives a better idea about the relationship between <code>total_reviews</code> and <code>rating</code> than a linear relationship.</p>
<p>Depending on the tool we used, we may also get information about our Adjusted <span class="math inline">\(R^2\)</span> (<strong>R-sq.(adj)</strong>) and <strong>Deviance explained</strong>, which is an analog to the unadjusted <span class="math inline">\(R^2\)</span> value for a Gaussian model. We also have <strong>GCV</strong> – the generalized cross validation score. It is an estimate of the mean square prediction error based on a leave-one-out cross validation estimation process. Naturally, the lower the GCV, the better the model.</p>
<p>TODO: NEED VISUAL</p>
<p>Beyond this the real approach to interpretation is in the visualization. We can use the <code>plot</code> function to get a sense of the relationship between our features and target.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(gam_model, <span class="at">se =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pygam.utils <span class="im">import</span> generate_X_grid</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>X_grid <span class="op">=</span> generate_X_grid(gam_model)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>plt.plot(X_grid, gam_model.predict(X_grid), color <span class="op">=</span> <span class="st">"#00AAFF"</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>plt.plot(X_grid, gam_model.prediction_intervals(X_grid), color <span class="op">=</span> <span class="st">"#00AAFF"</span>, ls <span class="op">=</span> <span class="st">'--'</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>plt.scatter(X, y, alpha <span class="op">=</span> <span class="fl">.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>Unfortunately the default package plots are not pretty, and sadly aren’t provided in the same way we’d expect for interpretation. But they’re fine for looking at your wiggly result. But we provide a better looking one<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. The main interpretation is that we’re mostly flat for total reviews less than the mean. At that point we get more of a positive linear effect, followed by a bit of a mixed bag for moviews with lots of total reviews.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-gam_plot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="linear_model_extensions_files/figure-html/fig-gam_plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;6.3: Visualizing a GAM</figcaption>
</figure>
</div>
</div>
</div>
<p>TODO: Move to estimation, but may need to nix for pdf brevity, and needs some work to fit well.</p>
</section>
<section id="sec-gam-splines" class="level3" data-number="6.3.4">
<h3 data-number="6.3.4" class="anchored" data-anchor-id="sec-gam-splines"><span class="header-section-number">6.3.4</span> Splines</h3>
<p>Now that you’ve gotten a taste of a standard way of specifying a GAM, let’s roll our own. We are going to need to generate several functions to make this work. The first will be to produce the <em>cubic spline</em>. Do take note that there are many different types of splines that could be used.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-7-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-1" role="tab" aria-controls="tabset-7-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-2" role="tab" aria-controls="tabset-7-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-7-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>cubic_spline <span class="ot">=</span> <span class="cf">function</span>(x, z) {</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  ((z <span class="sc">-</span> <span class="fl">0.5</span>)<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">12</span>) <span class="sc">*</span> ((x <span class="sc">-</span> <span class="fl">0.5</span>)<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">12</span>)<span class="sc">/</span><span class="dv">4</span> <span class="sc">-</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    ((<span class="fu">abs</span>(x <span class="sc">-</span> z) <span class="sc">-</span> <span class="fl">0.5</span>)<span class="sc">^</span><span class="dv">4</span> <span class="sc">-</span> (<span class="fu">abs</span>(x <span class="sc">-</span> z) <span class="sc">-</span> <span class="fl">0.5</span>)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span> <span class="sc">+</span> <span class="dv">7</span><span class="sc">/</span><span class="dv">240</span>) <span class="sc">/</span> <span class="dv">24</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-7-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> cubic_spline(x,z):</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (((z <span class="op">-</span> <span class="fl">0.5</span>)<span class="op">**</span><span class="dv">2</span> <span class="op">-</span> <span class="dv">1</span><span class="op">/</span><span class="dv">12</span>) <span class="op">*</span> ((x <span class="op">-</span> <span class="fl">0.5</span>)<span class="op">**</span><span class="dv">2</span> <span class="op">-</span> <span class="dv">1</span><span class="op">/</span><span class="dv">12</span>)<span class="op">/</span><span class="dv">4</span> <span class="op">-</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>            ((np.<span class="bu">abs</span>(x <span class="op">-</span> z) <span class="op">-</span> <span class="fl">0.5</span>)<span class="op">**</span><span class="dv">4</span> <span class="op">-</span> (np.<span class="bu">abs</span>(x <span class="op">-</span> z) <span class="op">-</span> <span class="fl">0.5</span>)<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> <span class="dv">2</span> <span class="op">+</span> <span class="dv">7</span><span class="op">/</span><span class="dv">240</span>) <span class="op">/</span> <span class="dv">24</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-gam-model-matrix" class="level3" data-number="6.3.5">
<h3 data-number="6.3.5" class="anchored" data-anchor-id="sec-gam-model-matrix"><span class="header-section-number">6.3.5</span> Model Matrix Function</h3>
<p>Then we a function to produce the model matrix:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-8-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-1" role="tab" aria-controls="tabset-8-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-2" role="tab" aria-controls="tabset-8-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-8-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>splX <span class="ot">=</span> <span class="cf">function</span>(x, knots) {</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  q <span class="ot">=</span> <span class="fu">length</span>(knots) <span class="sc">+</span> <span class="dv">2</span>        <span class="co"># number of parameters</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">=</span> <span class="fu">length</span>(x)                <span class="co"># number of observations</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  X <span class="ot">=</span> <span class="fu">matrix</span>(<span class="dv">1</span>, n, q)          <span class="co"># initialized model matrix</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  X[ ,<span class="dv">2</span>] <span class="ot">=</span> x                   <span class="co"># set second column to x</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  X[ ,<span class="dv">3</span><span class="sc">:</span>q] <span class="ot">=</span> <span class="fu">outer</span>(x, knots, <span class="at">FUN =</span> cubic_spline) </span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  X</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-8-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> splX(x, knots):</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>    q <span class="op">=</span> <span class="bu">len</span>(knots) <span class="op">+</span> <span class="dv">2</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">len</span>(x)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> np.ones((n, q))</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    X[:,<span class="dv">1</span>] <span class="op">=</span> x</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">2</span>, q):</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>        X[:,i] <span class="op">=</span> cubic_spline(x, knots[i<span class="op">-</span><span class="dv">2</span>])</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> X</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This model matrix will help us to produce an <em>unpenalized spline</em>.</p>
</div>
</div>
</div>
</section>
<section id="sec-gam-model-matrix" class="level3" data-number="6.3.6">
<h3 data-number="6.3.6" class="anchored" data-anchor-id="sec-gam-model-matrix"><span class="header-section-number">6.3.6</span> Model Matrix</h3>
<p>We can create a model with 4 knots – you can think of knots as places where individual regression lines will get joined together. You can always experiment with more or less knots. Once we have our knots ready, we can create the model matrix.</p>
<p>As soon as you create your <code>X</code> object, you should take a look at it. It will be a matrix with 4 columns. The first column will be all 1s, the second column will be the scaled <code>user_age</code>, and the last two columns will be the cubic splines.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-9-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-1" role="tab" aria-controls="tabset-9-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-9-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-2" role="tab" aria-controls="tabset-9-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-9-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>knots <span class="ot">=</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span><span class="sc">/</span><span class="dv">5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>rating <span class="ot">=</span> reviews<span class="sc">$</span>rating</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span> reviews<span class="sc">$</span>total_reviews_sc</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>X <span class="ot">=</span> <span class="fu">splX</span>(x, knots)            </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(X)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1]       [,2]          [,3]          [,4]          [,5]          [,6]
[1,]    1 -0.8272845  4.153406e-03 -0.0326229161 -0.0448777445 -0.0392293550
[2,]    1  0.9402239  3.231161e-05 -0.0032068475 -0.0027357582  0.0009673706
[3,]    1 -1.1641541 -4.416516e-03 -0.0803004886 -0.1235780974 -0.1435625745
[4,]    1  0.4683950 -3.548729e-04  0.0027291926  0.0023541418 -0.0007952384
[5,]    1  0.3940441  2.496222e-04  0.0027093841  0.0015964818 -0.0011544588
[6,]    1  0.7781318 -1.099612e-03 -0.0008054941  0.0006053991  0.0013598650</code></pre>
</div>
</div>
</div>
<div id="tabset-9-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-9-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>knots <span class="op">=</span> np.arange(<span class="dv">1</span>, <span class="dv">5</span>) <span class="op">/</span> <span class="dv">5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> reviews[<span class="st">'total_reviews_sc'</span>]</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>rating <span class="op">=</span> reviews[<span class="st">'rating'</span>]</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> splX(x, knots)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>X[:<span class="dv">5</span>,:]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>array([[ 1.00000000e+00, -8.27284454e-01,  4.15340591e-03,
        -3.26229161e-02, -4.48777445e-02, -3.92293550e-02],
       [ 1.00000000e+00,  9.40223866e-01,  3.23116121e-05,
        -3.20684754e-03, -2.73575817e-03,  9.67370635e-04],
       [ 1.00000000e+00, -1.16415406e+00, -4.41651564e-03,
        -8.03004886e-02, -1.23578097e-01, -1.43562575e-01],
       [ 1.00000000e+00,  4.68394990e-01, -3.54872863e-04,
         2.72919264e-03,  2.35414179e-03, -7.95238367e-04],
       [ 1.00000000e+00,  3.94044062e-01,  2.49622200e-04,
         2.70938406e-03,  1.59648177e-03, -1.15445884e-03]])</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-gam-model-fitting" class="level3" data-number="6.3.7">
<h3 data-number="6.3.7" class="anchored" data-anchor-id="sec-gam-model-fitting"><span class="header-section-number">6.3.7</span> Model Fitting</h3>
<p>Now that we have a model matrix, <code>X</code>, we can fit the model. All of the hardwork was done in creating the model matrix and we can just use <code>lm</code> or <code>OLS</code> to fit the model.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-10-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-1" role="tab" aria-controls="tabset-10-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-10-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-2" role="tab" aria-controls="tabset-10-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-10-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-10-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>fit_lm <span class="ot">=</span> <span class="fu">lm</span>(rating <span class="sc">~</span> X <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>fit_lm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rating ~ X - 1)

Coefficients:
      X1        X2        X3        X4        X5        X6  
  2.9776    0.3493   31.7281  -99.7536  101.4611  -34.2938  </code></pre>
</div>
</div>
</div>
<div id="tabset-10-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-10-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>fit_lm <span class="op">=</span> sm.OLS(rating, X).fit()</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>fit_lm.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>OLS Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>rating</td>
<td data-quarto-table-cell-role="th">R-squared:</td>
<td>0.116</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>OLS</td>
<td data-quarto-table-cell-role="th">Adj. R-squared:</td>
<td>0.111</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>Least Squares</td>
<td data-quarto-table-cell-role="th">F-statistic:</td>
<td>26.03</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Sun, 17 Dec 2023</td>
<td data-quarto-table-cell-role="th">Prob (F-statistic):</td>
<td>9.31e-25</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>20:09:37</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-893.05</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>1000</td>
<td data-quarto-table-cell-role="th">AIC:</td>
<td>1798.</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>994</td>
<td data-quarto-table-cell-role="th">BIC:</td>
<td>1828.</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>5</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">t</td>
<td data-quarto-table-cell-role="th">P&gt;|t|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">const</td>
<td>2.9776</td>
<td>0.050</td>
<td>59.862</td>
<td>0.000</td>
<td>2.880</td>
<td>3.075</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">x1</td>
<td>0.3493</td>
<td>0.057</td>
<td>6.136</td>
<td>0.000</td>
<td>0.238</td>
<td>0.461</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">x2</td>
<td>31.7281</td>
<td>13.952</td>
<td>2.274</td>
<td>0.023</td>
<td>4.349</td>
<td>59.107</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">x3</td>
<td>-99.7536</td>
<td>45.771</td>
<td>-2.179</td>
<td>0.030</td>
<td>-189.573</td>
<td>-9.934</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">x4</td>
<td>101.4611</td>
<td>45.666</td>
<td>2.222</td>
<td>0.027</td>
<td>11.849</td>
<td>191.073</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">x5</td>
<td>-34.2938</td>
<td>14.781</td>
<td>-2.320</td>
<td>0.021</td>
<td>-63.300</td>
<td>-5.288</td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Omnibus:</td>
<td>5.602</td>
<td data-quarto-table-cell-role="th">Durbin-Watson:</td>
<td>2.081</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(Omnibus):</td>
<td>0.061</td>
<td data-quarto-table-cell-role="th">Jarque-Bera (JB):</td>
<td>4.333</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Skew:</td>
<td>-0.036</td>
<td data-quarto-table-cell-role="th">Prob(JB):</td>
<td>0.115</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Kurtosis:</td>
<td>2.686</td>
<td data-quarto-table-cell-role="th">Cond. No.</td>
<td>3.64e+03</td>
</tr>
</tbody>
</table>
<br><br>Notes:<br>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.<br>[2] The condition number is large, 3.64e+03. This might indicate that there are<br>strong multicollinearity or other numerical problems.
</div>
</div>
</div>
</div>
</div>
</section>
<section id="prediction" class="level3" data-number="6.3.8">
<h3 data-number="6.3.8" class="anchored" data-anchor-id="prediction"><span class="header-section-number">6.3.8</span> Prediction</h3>
<p>We can set some prediction values for this model:</p>
<p>TODO: fix this to reflect total reviews, not 0:1; Don’t worry until we know where it goes.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-11-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-11-1" role="tab" aria-controls="tabset-11-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-11-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-11-2" role="tab" aria-controls="tabset-11-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-11-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-11-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># xp = seq(0, 1, by = .01)</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>xp <span class="ot">=</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>, <span class="at">by =</span> .<span class="dv">01</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>Xp <span class="ot">=</span> <span class="fu">splX</span>(xp, knots)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-11-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-11-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>xp <span class="op">=</span> np.arange(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.01</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>Xp <span class="op">=</span> splX(xp, knots)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>While creating those predictions is nice, using them to visualize the model is far more helpful.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-spline_viz" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="linear_model_extensions_files/figure-html/fig-spline_viz-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;6.4: Visualizing cubic regression spline</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-spline_viz" class="quarto-xref">Figure&nbsp;<span>6.4</span></a>, we can see that the relationship starts a bit flat, increases, and then flattens out again. This is a pretty good example of a nonlinear relationship.</p>
</section>
<section id="sec-gam-penalty" class="level3" data-number="6.3.9">
<h3 data-number="6.3.9" class="anchored" data-anchor-id="sec-gam-penalty"><span class="header-section-number">6.3.9</span> Penalized Cubic Spline</h3>
<p>Recall that this is an unpenalized cubic spline. If we want to have a finer degree of control over that wiggly line, we can include a <strong>lambda penalty</strong>.</p>
<p>We’ll need to change up our spline function just a bit.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-12-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-12-1" role="tab" aria-controls="tabset-12-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-12-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-12-2" role="tab" aria-controls="tabset-12-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-12-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-12-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>splS <span class="ot">=</span> <span class="cf">function</span>(knots) {</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  q <span class="ot">=</span> <span class="fu">length</span>(knots) <span class="sc">+</span> <span class="dv">2</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  S <span class="ot">=</span> <span class="fu">matrix</span>(<span class="dv">0</span>, q, q) </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  S[<span class="dv">3</span><span class="sc">:</span>q, <span class="dv">3</span><span class="sc">:</span>q] <span class="ot">=</span> <span class="fu">outer</span>(knots, knots, <span class="at">FUN =</span> cubic_spline)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  S</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-12-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-12-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> splS(knots):</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>    q <span class="op">=</span> <span class="bu">len</span>(knots) <span class="op">+</span> <span class="dv">2</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    S <span class="op">=</span> np.zeros((q, q))</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    S[<span class="dv">2</span>:, <span class="dv">2</span>:] <span class="op">=</span> cubic_spline(knots, knots[:,<span class="va">None</span>])</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> S</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>We also need to be able to take the square root of our entire matrix. This is a bit more complicated than it sounds. We need to take the eigenvalue decomposition of the matrix, take the square root of the eigenvalues, and then recombine the matrix.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-13-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-13-1" role="tab" aria-controls="tabset-13-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-13-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-13-2" role="tab" aria-controls="tabset-13-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-13-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-13-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>mat_sqrt <span class="ot">=</span> <span class="cf">function</span>(S) {</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">=</span> <span class="fu">eigen</span>(S, <span class="at">symmetric =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  rS <span class="ot">=</span> d<span class="sc">$</span>vectors <span class="sc">%*%</span> <span class="fu">diag</span>(d<span class="sc">$</span>values<span class="sc">^</span>.<span class="dv">5</span>) <span class="sc">%*%</span> <span class="fu">t</span>(d<span class="sc">$</span>vectors)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  rS</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-13-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-13-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> mat_sqrt(S):</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>    w, v <span class="op">=</span> np.linalg.eig(S)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    rS <span class="op">=</span> v <span class="op">@</span> np.diag(w<span class="op">**</span><span class="fl">.5</span>) <span class="op">@</span> v.T</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> rS</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-gam-penalty-model" class="level3" data-number="6.3.10">
<h3 data-number="6.3.10" class="anchored" data-anchor-id="sec-gam-penalty-model"><span class="header-section-number">6.3.10</span> Penalized Model Fitting Function</h3>
<p>With those functions in hand, we can create the function to fit the entire model.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-14-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-14-1" role="tab" aria-controls="tabset-14-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-14-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-14-2" role="tab" aria-controls="tabset-14-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-14-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-14-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>prs_fit <span class="ot">=</span> <span class="cf">function</span>(y, x, knots, lambda) {</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  q  <span class="ot">=</span> <span class="fu">length</span>(knots) <span class="sc">+</span> <span class="dv">2</span>    <span class="co"># dimension of basis</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  n  <span class="ot">=</span> <span class="fu">length</span>(x)            <span class="co"># number of observations</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  Xa <span class="ot">=</span> <span class="fu">rbind</span>(<span class="fu">splX</span>(x, knots), <span class="fu">mat_sqrt</span>(<span class="fu">splS</span>(knots))<span class="sc">*</span><span class="fu">sqrt</span>(lambda)) <span class="co"># augmented model matrix</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  y[(n <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span>(n<span class="sc">+</span>q)] <span class="ot">=</span> <span class="dv">0</span>      <span class="co"># augment the data vector</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(y <span class="sc">~</span> Xa <span class="sc">-</span> <span class="dv">1</span>) <span class="co"># fit and return penalized regression spline</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-14-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-14-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> prs_fit(y, x, knots, lamba):</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>    q <span class="op">=</span> <span class="bu">len</span>(knots) <span class="op">+</span> <span class="dv">2</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">len</span>(x)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>    Xa <span class="op">=</span> np.vstack(</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>      (splX(x, knots), mat_sqrt(splS(knots))<span class="op">*</span>np.sqrt(lamba))</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>    y_add <span class="op">=</span> np.zeros(q)</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> y.to_numpy()</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> np.concatenate((y, y_add), axis <span class="op">=</span> <span class="dv">0</span>)</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> sm.OLS(y, Xa).fit()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>Notice again that magic happens in the model matrix, but that we are still just using <code>lm</code> or <code>OLS</code> to fit the model.</p>
</section>
<section id="sec-gam-penalty-fitting" class="level3" data-number="6.3.11">
<h3 data-number="6.3.11" class="anchored" data-anchor-id="sec-gam-penalty-fitting"><span class="header-section-number">6.3.11</span> Penalized Model Fitting</h3>
<p>Let’s stick with 4 knots and see what happens when we set our lambda to .1:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-15-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-15-1" role="tab" aria-controls="tabset-15-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-15-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-15-2" role="tab" aria-controls="tabset-15-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-15-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-15-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>knots <span class="ot">=</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span><span class="sc">/</span><span class="dv">5</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>fit_penalized <span class="ot">=</span> <span class="fu">prs_fit</span>(</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> rating,</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> x,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">knots =</span> knots,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">lambda =</span> .<span class="dv">1</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>) </span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>Xp <span class="ot">=</span> <span class="fu">splX</span>(xp, knots) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-15-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-15-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>knots <span class="op">=</span> np.arange(<span class="dv">1</span>, <span class="dv">5</span>)<span class="op">/</span><span class="dv">5</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>fit_penalized <span class="op">=</span> prs_fit(</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> y,</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> x,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>    knots <span class="op">=</span> knots,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>    lamba <span class="op">=</span> <span class="fl">.1</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>Xp <span class="op">=</span> splX(xp, knots)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>As shown in <a href="#fig-r_lambda_1_viz" class="quarto-xref">Figure&nbsp;<span>6.5</span></a>, there is some wiggle to that line, but it is not as extreme as what we saw with our unpenalized cubic spline.</p>
<p>TODO: fix plot scale (doesn’t match raw or scaled data)</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-r_lambda_1_viz" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="linear_model_extensions_files/figure-html/fig-r_lambda_1_viz-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;6.5: GAM model with lambda set to .1</figcaption>
</figure>
</div>
</div>
</div>
<p>We can test out what happens at different lambda values:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-lambda_value_viz" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="linear_model_extensions_files/figure-html/fig-lambda_value_viz-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;6.6: GAM model with different lambda values</figcaption>
</figure>
</div>
</div>
</div>
<p>What can we take from <a href="#fig-lambda_value_viz" class="quarto-xref">Figure&nbsp;<span>6.6</span></a>? As lambda values get closer to 1, we see lines that look very similar to a standard linear model. If you recall the our function to fit the model, we multiplied the square root of the matrix by the square root of the lambda value; since the square root of 1 is 1, we wouldn’t see anything too interesting happen. As our lambda value gets lower, we see an increasing amount of wiggle happen.</p>
<p>Naturally, this is a great time to think about how these models would work on new data. As lambda gets smaller, we are fitting our in-sample data much better. How do you think this would fare with unseen data? If you’d say that we would do well with training and horrible on testing, we’d likely agree with you.</p>
</section>
</section>
<section id="sec-mixed-models" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="sec-mixed-models"><span class="header-section-number">6.4</span> Mixed Models</h2>
<section id="sec-mixed-models-why" class="level3" data-number="6.4.1">
<h3 data-number="6.4.1" class="anchored" data-anchor-id="sec-mixed-models-why"><span class="header-section-number">6.4.1</span> Why Should You Care?</h3>
<p>Structures within your data are important and paying attention to how data might be grouped in some way will let you generate more insights about how observations within and between groups might behave. For example, people working in the same organization, or students in the same school, are likely to have a more similar experiences than those from different organizations or schools. This shared connection within groups may ultimately affect what we see in our chosen outcomes. Mixed models will let us handle grouped data such as this, all while getting the benefits of a standard linear model.</p>
</section>
<section id="sec-mixed-models-knowing" class="level3" data-number="6.4.2">
<h3 data-number="6.4.2" class="anchored" data-anchor-id="sec-mixed-models-knowing"><span class="header-section-number">6.4.2</span> Knowing Your Data</h3>
<p>As much fun as modeling is, knowing your data is far more important. You can throw any model you want at your data, from simple to fancy, but you can count on disappointment if you don’t fundamentally know the structures that live within your data. Let’s take a quick look at the following visualizations:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-year-release-rating" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="linear_model_extensions_files/figure-html/fig-year-release-rating-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;6.7: Linear relationship between year of movie release and rating.</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-year-release-rating" class="quarto-xref">Figure&nbsp;<span>6.7</span></a>, we see a pretty solid positive relationship between the total number of reviews and ratings. We could probably just stop there, but we might be ignoring something substantial within our data: genre. We might want to ask a question, “Does this relationship work the same way across the different genre?”</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-year-release-genre-rating" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="linear_model_extensions_files/figure-html/fig-year-release-genre-rating-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;6.8: Linear relationship between year of movie release and rating, with genre.</figcaption>
</figure>
</div>
</div>
</div>
<p>A very quick examination of <a href="#fig-year-release-genre-rating" class="quarto-xref">Figure&nbsp;<span>6.8</span></a> might suggest that the relationship between user age and rating varies significantly over the different genres. Most genres show a positive relationship, while one (<code>other</code>) shows a negative relationship, and all with various levels of strength.</p>
<p>Just for fun, try to group by genre and summarize it by the mean rating. You’ll find that the averages are very different across the genre! Then, subtract the overal mean rating from those values, so that they represent deviations from the mean. Keep them handy!</p>
<p>Clearly, genre is offering some type of additional information to the model, but how can we incorporate that information into our model? An interaction might come to find at first, and that’s the right way to think about it. A <strong>mixed model</strong> can be used to incorporate that information, which is largely a group interaction, into our model, without much hassle and with a huge boost in explanability.</p>
<p>The term <strong>mixed model</strong> is as vanilla as we can possibly make it, but you might have heard of different flavors of them before. You might have heard of <em>Hierarchical Linear Models</em>, or even <em>multilevel models</em>, or heard <em>mixed-effects models</em> tossed around before. Maybe you’ve even be exposed to ideas like <em>random effects</em> or <em>random slopes</em>. No matter what word you say, they are all instances of what we’ll call a <strong>mixed model</strong>.</p>
<p>What makes a model a mixed model? The mixed model is characterized by the idea that a model can have <em>fixed</em> and <em>random</em> effects. Fortunately, you’ve already encountered <em>fixed</em> effects – those are the features that we have been using in all of our models so far! In the mixed model context, the <em>random effect</em>, typically comes from some type of grouping variable that contributes to unique variance in the outcome and we are going to let them vary from the rest of the model. Grouping variables can be actual groups, with the classic example being students in a classroom. Those groups can also be nested within larger groups – students nested within classrooms, nested within schools, nested within districts. These groups can also capture the notion of a repeated measure for an individual, like repeated test scores.</p>
<p>While we aren’t rejecting the idea of a mean with these mixed-models, we are implying that each group (whether it is a group, nested group, or repeated observations from a person) has its own unique mean that can be useful for modeling the target. Formally, we might specify something like this:</p>
<p><span class="math display">\[
\textrm{rating} = b_{\textrm{0\_genre}} + b_\textrm{year}*\textrm{year}
\]</span></p>
<p>We are explicitly saying that genre has its own unique effect for this model in the form of specific intercepts for each genre. We also posit that those come from a <em>random</em> distribution. We can specify that as:</p>
<p><span class="math display">\[b_{\textrm{0\_genre}} \sim \textrm{N}(b_\textrm{intercept}, \sigma_\textrm{genre})\]</span></p>
<p>This means that the random intercepts will be normally distributed and the overall intercept is just the mean of those random intercepts, and with its own variance, an extra paramter we’ll eventually have to estimate as part of the model. Another very common depiction is:</p>
<p><span class="math display">\[\textrm{re\_group} \sim \textrm{N}(0, \sigma_\textrm{genre})\]</span></p>
<p><span class="math display">\[b_{\textrm{0\_genre}} = b_\textrm{intercept} +\textrm{re\_group}\]</span></p>
<p>TODO: Need another example?</p>
<p>Before we go to modeling our reviews, let’s consider an example training program to increase vertical jump, with average vertical increases of 2 inches. That really doesn’t sound all that impressive; however, that increase came across 5 distinct groups: NBA players, NFL players, NHL players, MLB players, and data analysts. We can be pretty certain that each group has a very different vertical jump distribution coming into this training program. Given the amount of jumping that NBA players do, this program is unlikely to produce dramatic increases in vertical jump for them. We would probably expect modest gains in the NFL and even greater gains within NHL and MLB players. Where we are going to see the best gains, though, is from data analysts – they might want to jump to conclusions, but don’t need to jump over their computers very often. Now that we know the additional information, can we just look at the average increase and be satisfied? Probably not. Instead, we need to look at the group that individuals might be in and judge accordingly. A mixed-model is going to let us to model all of this without too much work.</p>
<p>You might be asking? Why don’t I just put genre into the model like other categorical features? In the case of genre, that’s okay, but consider thousands of county voting percentages for an election, would you just put a county indicator into the model as is? Mixed models provide several advantages:</p>
<ul>
<li>Any coefficient can be allowed to vary by groups, including other random effects. It actually is just an interaction in the end.</li>
<li>The group-specific effects are penalized, which shrinks them toward the overall mean. This helps to avoid overfitting, and that penalty is related to the variance estimate of the random effect. In other words, you’re just running a penalized linear model where the penalty is applied to the group-specific effects.</li>
<li>Standard modeling approaches only estimate the variance, and get the estimated group effects via a predictive method. This allows only one additional parameter to estimate rather than a weight or coefficient for every group.</li>
<li>The group effects are like a very simplified <strong>embedding</strong>, where we have taken a cateogrical feature and turned it into a numeric one. This will help you understand techniques that are used in other places like deep learning.</li>
<li>When you start to think aobut random effects and/or distributions for effects, you’re already thinking like a Bayesian, who is always thinking about the distributions for various effects. Mixed models are a perfect segue from standard linear model estimation to Bayesian estimation.</li>
<li>The random effect is akin to a latent variable of ‘unspecified group causes’. This is a very powerful idea that can be used in many different ways, but importantly, you might want to start thinking about how you can figure out what those ‘unspecified’ causes may be!</li>
<li>Group effects will almost always improve your model’s performance relative to not having them, especially if you weren’t including those groups in your model because of how many there were.</li>
</ul>
<p>In short, mixed models are a fun way to incorporate additional interpretive color to your model, while also getting several additional benefits!</p>
</section>
<section id="sec-mixed-models-standard" class="level3" data-number="6.4.3">
<h3 data-number="6.4.3" class="anchored" data-anchor-id="sec-mixed-models-standard"><span class="header-section-number">6.4.3</span> Standard Functions</h3>
<p>Now let’s fit some mixed models with <code>lme4</code> or <code>statsmodels</code>. We will also create <code>null models</code> (i.e., models with an intercept only), since we will need some infomration from them later.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-16-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-16-1" role="tab" aria-controls="tabset-16-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-16-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-16-2" role="tab" aria-controls="tabset-16-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-16-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-16-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>fit_mer <span class="ot">=</span> <span class="fu">lmer</span>(rating <span class="sc">~</span> total_reviews_sc <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> genre), </span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>               reviews, </span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_mer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: rating ~ total_reviews_sc + (1 | genre)
   Data: reviews

     AIC      BIC   logLik deviance df.resid 
  1506.6   1526.2   -749.3   1498.6      996 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.0992 -0.6840  0.0465  0.7187  3.1890 

Random effects:
 Groups   Name        Variance Std.Dev.
 genre    (Intercept) 0.08309  0.2882  
 Residual             0.25482  0.5048  
Number of obs: 1000, groups:  genre, 8

Fixed effects:
                 Estimate Std. Error t value
(Intercept)        2.9782     0.1038   28.69
total_reviews_sc   0.2479     0.0164   15.12

Correlation of Fixed Effects:
            (Intr)
ttl_rvws_sc -0.005</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>null_model <span class="ot">=</span> <span class="fu">lmer</span>(rating <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> genre), </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>                   reviews, </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(null_model, <span class="at">correlation =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: rating ~ 1 + (1 | genre)
   Data: reviews

     AIC      BIC   logLik deviance df.resid 
  1710.2   1724.9   -852.1   1704.2      997 

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-3.08192 -0.76091 -0.04675  0.66740  2.98841 

Random effects:
 Groups   Name        Variance Std.Dev.
 genre    (Intercept) 0.07557  0.2749  
 Residual             0.31371  0.5601  
Number of obs: 1000, groups:  genre, 8

Fixed effects:
            Estimate Std. Error t value
(Intercept)  2.98593    0.09962   29.98</code></pre>
</div>
</div>
</div>
<div id="tabset-16-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-16-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>fit_mer <span class="op">=</span> sm.MixedLM.from_formula(<span class="st">"rating ~ total_reviews_sc"</span>, reviews, </span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>                                  groups<span class="op">=</span>reviews[<span class="st">"genre"</span>])</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>fit_mer <span class="op">=</span> fit_mer.fit()</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>fit_mer.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td>Model:</td>
<td>MixedLM</td>
<td>Dependent Variable:</td>
<td>rating</td>
</tr>
<tr class="even">
<td>No. Observations:</td>
<td>1000</td>
<td>Method:</td>
<td>REML</td>
</tr>
<tr class="odd">
<td>No. Groups:</td>
<td>8</td>
<td>Scale:</td>
<td>0.2551</td>
</tr>
<tr class="even">
<td>Min. group size:</td>
<td>49</td>
<td>Log-Likelihood:</td>
<td>-753.8114</td>
</tr>
<tr class="odd">
<td>Max. group size:</td>
<td>300</td>
<td>Converged:</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>Mean group size:</td>
<td>125.0</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">Coef.</td>
<td data-quarto-table-cell-role="th">Std.Err.</td>
<td data-quarto-table-cell-role="th">z</td>
<td data-quarto-table-cell-role="th">P&gt;|z|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Intercept</td>
<td>2.978</td>
<td>0.111</td>
<td>26.863</td>
<td>0.000</td>
<td>2.761</td>
<td>3.195</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">total_reviews_sc</td>
<td>0.248</td>
<td>0.016</td>
<td>15.114</td>
<td>0.000</td>
<td>0.216</td>
<td>0.280</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Group Var</td>
<td>0.095</td>
<td>0.104</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<br>

</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>null_model <span class="op">=</span> sm.MixedLM.from_formula(<span class="st">"rating ~ 1"</span>, reviews, </span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>                                     groups<span class="op">=</span>reviews[<span class="st">"genre"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>What can we take from these summaries, and what are we getting beyond the linear model?</p>
<p>For starters, we should notice a change in our standard errors – by integrating information about the groups, we are getting a better sense of how much uncertainty our model contains at the global average level.</p>
<p>We also see some additional information for our random effects. The standard deviation is telling us how much the rating moves around based upon genre after getting the information from our fixed effects (i.e., the rating can move around nearly .3 points from genre alone).</p>
<p>We can use information for the random effects components to get some additional information. For instance, we can calculate the proportion of variance in scores that is accounted for by the genre alone:</p>
<p><span class="math display">\[\frac{\text{intercept variance}}{\text{intercept variance} + \text{residual variance}}\]</span></p>
<p>With our values, we have:</p>
<p><span class="math display">\[
.08309 / (.08309 + .25482) = 0.2458939
\]</span></p>
<p>This is what is known as the intraclass correlation (ICC). It ranges from 0 (no variance between clusters) to 1 (variance between clusters). With an ICC of .25, we can say that 25% of the variance in scores is accounted for by the genre alone.</p>
<p>TODO: WEED PULLING</p>
<p>We can also use various bits of information in our output to create different <em>R^2</em> values.</p>
<p>For the first level of the model, we can calculate the <span class="math inline">\(R^2\)</span> as:</p>
<p><span class="math display">\[R^2_1 - \frac{\sigma^2_{M1} + \tau^2_{M1}}{\sigma^2_{M0} + \tau^2_{M0}}\]</span></p>
<p>We can pull that information from our two model outputs:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>m1Sigma <span class="ot">=</span> .<span class="dv">08309</span> <span class="co"># full model random effect intercept</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>m1Tau <span class="ot">=</span> .<span class="dv">25482</span> <span class="co"># full model random effect residual</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>m0Sigma <span class="ot">=</span> .<span class="dv">07557</span> <span class="co"># null model random effect intercept</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>m0Tau <span class="ot">=</span> .<span class="dv">31371</span> <span class="co"># null model random effect residual</span></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> ((m1Sigma <span class="sc">+</span> m1Tau) <span class="sc">/</span> (m0Sigma <span class="sc">+</span> m0Tau))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1319616</code></pre>
</div>
</div>
<p>The fixed effect of number of reviews accounts for nearly 13% of the variation within the reviews.</p>
<p>The second level can be calculated as:</p>
<p><span class="math display">\[R^2_2 = 1 - \frac{\sigma^2_{M1} / B + \tau^2_{M1}}{\sigma^2_{M0} / B + \tau^2_{M0}}\]</span></p>
<p>We see that we added a <em>B</em> into the mix here and it is just the average size of the level 2 units (1000 observations / 8 genres).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>level2Mean <span class="ot">=</span> <span class="dv">1000</span> <span class="sc">/</span> <span class="dv">8</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>r2Numerator <span class="ot">=</span> m1Sigma <span class="sc">/</span> level2Mean <span class="sc">+</span> m1Tau</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>r2Denominator <span class="ot">=</span> m0Sigma <span class="sc">/</span> level2Mean <span class="sc">+</span> m0Tau</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> (r2Numerator <span class="sc">/</span> r2Denominator)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1871687</code></pre>
</div>
</div>
<p>Which gives us .18 or 18% of the variation in scores is accounted for by the genre alone.</p>
<p>You can also get these values in R like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">r2</span>(fit_mer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># R2 for Mixed Models

  Conditional R2: 0.362
     Marginal R2: 0.154</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>MuMIn<span class="sc">::</span><span class="fu">r.squaredGLMM</span>(fit_mer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           R2m       R2c
[1,] 0.1539124 0.3619545</code></pre>
</div>
</div>
<p>Here we have two values: the marginal R2 (R2m) and the conditional R2 (R2c). You can think of the marginal values as the standard type of R2 – it is the variability explained by the fixed effects part of the model (it is what we have already done above). The conditional R2 is using both fixed and random effects, so you can think of it as the toal variability explained. Clearly, we can subtract the two to get a better understanding of the effect of the random effects. With <span class="math inline">\(.362 - .154 = .208\)</span>, we can say that the random effects account for 20.8% of the variation in ratings.</p>
<p>Notice that those values are a bit different than what we produced by hand. Packages are now using a revised method proposed by Nakagawa, Johnson, and Schielzeth (2017) that is a bit more accurate than the previous method.</p>
<p>We can also get a good sense of the random effect estimates:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-random_effects" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="linear_model_extensions_files/figure-html/fig-random_effects-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;6.9: Random effects estimates</figcaption>
</figure>
</div>
</div>
</div>
<p>For <a href="#fig-random_effects" class="quarto-xref">Figure&nbsp;<span>6.9</span></a>, the easiest way to think about it is that the values are effects for each individual random effect (i.e., each genre’s random intercept). Since we are just dealing with intercepts right now, they are the deviations from the fixed intercept. The intercept for the model is ~2.6 and the random effect for <code>comedy</code> is .48. If we wanted to predict scores for a comedy movie, we would take 2.6 + .48 for the intercept portion of the model (the same would go for any random slopes in the model). In the end, it is showing how much the intercept shifts from genre to genre, and some genres have a positive effect beyond the average and others have a negative effect (<code>sci-fi</code>, for instance, is well below the global average).</p>
<p>Remember your group-by and summarize task earlier? Each point is the difference between a genre’s average and the overall average – values in blue are higher than the average and values in red are lower than the average. With that, the average rating for <code>comedy</code> is much better than the global average rating, while <code>sci-fi</code> is much worse than the global average rating.</p>
</section>
<section id="model-matrix" class="level3" data-number="6.4.4">
<h3 data-number="6.4.4" class="anchored" data-anchor-id="model-matrix"><span class="header-section-number">6.4.4</span> Model Matrix</h3>
<p>Let’s start our homebrewing adventures by creating a model matrix. We are going to use the <code>model.matrix()</code> function to create our model matrix. We are going to use the <code>user_age</code> variable as our fixed effect and <code>genre</code> as our random effect. We are going to use the <code>factor()</code> function to make sure that <code>genre</code> is treated as a categorical variable. We are also going to use the <code>-1</code> to remove the intercept from the model matrix.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-17-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-17-1" role="tab" aria-controls="tabset-17-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-17-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-17-2" role="tab" aria-controls="tabset-17-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-17-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-17-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">=</span> <span class="fu">model.matrix</span>(<span class="sc">~</span>total_reviews_sc, reviews)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>Z <span class="ot">=</span> <span class="fu">model.matrix</span>(<span class="sc">~</span><span class="fu">factor</span>(reviews<span class="sc">$</span>genre) <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(Z) <span class="ot">=</span> <span class="fu">paste0</span>(<span class="st">"released_"</span>, <span class="fu">sort</span>(<span class="fu">unique</span>(reviews<span class="sc">$</span>genre)))</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>y <span class="ot">=</span> reviews<span class="sc">$</span>rating</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-17-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-17-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> reviews[[<span class="st">'total_reviews_sc'</span>]]</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(X)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> X.to_numpy()</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>Z <span class="op">=</span> pd.get_dummies(reviews[<span class="st">'genre'</span>], drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>Z <span class="op">=</span> Z.to_numpy()</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> reviews[<span class="st">'rating'</span>]</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> y.to_numpy()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
<section id="likelihood-function" class="level3" data-number="6.4.5">
<h3 data-number="6.4.5" class="anchored" data-anchor-id="likelihood-function"><span class="header-section-number">6.4.5</span> Likelihood Function</h3>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-18-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-18-1" role="tab" aria-controls="tabset-18-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-18-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-18-2" role="tab" aria-controls="tabset-18-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-18-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-18-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>mixed_log_likelihood <span class="ot">=</span> <span class="cf">function</span>(y, X, Z, theta) {</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  tau   <span class="ot">=</span> <span class="fu">exp</span>(theta[<span class="dv">1</span>])</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  sigma <span class="ot">=</span> <span class="fu">exp</span>(theta[<span class="dv">2</span>])</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">=</span> <span class="fu">length</span>(y)</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># evaluate covariance matrix for y</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>  e  <span class="ot">=</span> <span class="fu">tcrossprod</span>(Z)<span class="sc">*</span>tau<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="fu">diag</span>(n)<span class="sc">*</span>sigma<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>  b  <span class="ot">=</span> <span class="fu">coef</span>(<span class="fu">lm.fit</span>(X, y))</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>  mu <span class="ot">=</span> X <span class="sc">%*%</span> b</span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>  ll <span class="ot">=</span> mvtnorm<span class="sc">::</span><span class="fu">dmvnorm</span>(y, mu, e, <span class="at">log =</span> <span class="cn">TRUE</span>)</span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>  <span class="sc">-</span>ll</span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-18-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-18-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> mixed_log_likelihood(theta, y, X, Z):</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>    tau <span class="op">=</span> np.exp(theta[<span class="dv">0</span>])</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>    sigma <span class="op">=</span> np.exp(theta[<span class="dv">1</span>])</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">len</span>(y)</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>    e <span class="op">=</span> (Z.dot(Z.T) <span class="op">*</span> tau<span class="op">**</span><span class="dv">2</span>) <span class="op">+</span> (np.eye(n) <span class="op">*</span> sigma<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>    b <span class="op">=</span> np.linalg.lstsq(X, y, rcond<span class="op">=</span><span class="va">None</span>)[<span class="dv">0</span>]</span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>    mu <span class="op">=</span> X.dot(b) </span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a>    ll <span class="op">=</span> stats.multivariate_normal.logpdf(y, mu, e)</span>
<span id="cb62-13"><a href="#cb62-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>ll</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
<section id="model-fitting" class="level3" data-number="6.4.6">
<h3 data-number="6.4.6" class="anchored" data-anchor-id="model-fitting"><span class="header-section-number">6.4.6</span> Model Fitting</h3>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-19-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-19-1" role="tab" aria-controls="tabset-19-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-19-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-19-2" role="tab" aria-controls="tabset-19-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-19-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-19-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>param_init <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(param_init) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">'tau'</span>, <span class="st">'sigma'</span>)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">=</span> <span class="fu">optim</span>(</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">fn  =</span> mixed_log_likelihood,</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">X   =</span> X,</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">y   =</span> y,</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Z   =</span> Z,</span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">par =</span> param_init,</span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># control = list(reltol = 1e-10)</span></span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-14"><a href="#cb63-14" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(fit<span class="sc">$</span>par) <span class="co"># compare to sd of random effects</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      tau     sigma 
0.2938593 0.5064417 </code></pre>
</div>
</div>
</div>
<div id="tabset-19-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-19-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> optimize <span class="im">as</span> opt</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> mixed_log_likelihood(theta, y, X, Z):</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>    tau <span class="op">=</span> np.exp(theta[<span class="dv">0</span>])</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>    sigma <span class="op">=</span> np.exp(theta[<span class="dv">1</span>])</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">len</span>(y)</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>    e <span class="op">=</span> (Z.dot(Z.T) <span class="op">*</span> tau<span class="op">**</span><span class="dv">2</span>) <span class="op">+</span> (np.eye(n) <span class="op">*</span> sigma<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>    b <span class="op">=</span> np.linalg.lstsq(X, y, rcond<span class="op">=</span><span class="va">None</span>)[<span class="dv">0</span>]</span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>    mu <span class="op">=</span> X.dot(b) </span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a>    ll <span class="op">=</span> stats.multivariate_normal.logpdf(y, mu, e)</span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>ll</span>
<span id="cb65-13"><a href="#cb65-13" aria-hidden="true" tabindex="-1"></a>theta <span class="op">=</span> np.array([<span class="dv">0</span>, <span class="dv">0</span>])</span>
<span id="cb65-14"><a href="#cb65-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-15"><a href="#cb65-15" aria-hidden="true" tabindex="-1"></a>mixed_log_likelihood(theta, y, X, Z)</span>
<span id="cb65-16"><a href="#cb65-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-17"><a href="#cb65-17" aria-hidden="true" tabindex="-1"></a>fit <span class="op">=</span> opt.minimize(</span>
<span id="cb65-18"><a href="#cb65-18" aria-hidden="true" tabindex="-1"></a>    fun<span class="op">=</span>mixed_log_likelihood,</span>
<span id="cb65-19"><a href="#cb65-19" aria-hidden="true" tabindex="-1"></a>    x0<span class="op">=</span>theta,</span>
<span id="cb65-20"><a href="#cb65-20" aria-hidden="true" tabindex="-1"></a>    args<span class="op">=</span>(y, X, Z),</span>
<span id="cb65-21"><a href="#cb65-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># tol=1e-5</span></span>
<span id="cb65-22"><a href="#cb65-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb65-23"><a href="#cb65-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-24"><a href="#cb65-24" aria-hidden="true" tabindex="-1"></a>np.exp(fit.x) <span class="co"># compare to sd of random effects</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="performance-comparisons" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="performance-comparisons"><span class="header-section-number">6.5</span> Performance Comparisons</h2>
<p>Just for giggles, we should see how all of our models perform:</p>
<div class="cell">
<div id="fig-model_performance_comp" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<div id="oyukdmcecw" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>@import url("https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Libre+Franklin:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
#oyukdmcecw table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#oyukdmcecw thead, #oyukdmcecw tbody, #oyukdmcecw tfoot, #oyukdmcecw tr, #oyukdmcecw td, #oyukdmcecw th {
  border-style: none;
}

#oyukdmcecw p {
  margin: 0;
  padding: 0;
}

#oyukdmcecw .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#oyukdmcecw .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#oyukdmcecw .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#oyukdmcecw .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#oyukdmcecw .gt_heading {
  background-color: #FFFFFF;
  text-align: left;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#oyukdmcecw .gt_bottom_border {
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#oyukdmcecw .gt_col_headings {
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: none;
  border-bottom-width: 1px;
  border-bottom-color: #334422;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#oyukdmcecw .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 12px;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#oyukdmcecw .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 12px;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#oyukdmcecw .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#oyukdmcecw .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#oyukdmcecw .gt_column_spanner {
  border-bottom-style: none;
  border-bottom-width: 1px;
  border-bottom-color: #334422;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#oyukdmcecw .gt_spanner_row {
  border-bottom-style: hidden;
}

#oyukdmcecw .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#oyukdmcecw .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#oyukdmcecw .gt_from_md > :first-child {
  margin-top: 0;
}

#oyukdmcecw .gt_from_md > :last-child {
  margin-bottom: 0;
}

#oyukdmcecw .gt_row {
  padding-top: 7px;
  padding-bottom: 7px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#oyukdmcecw .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#oyukdmcecw .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#oyukdmcecw .gt_row_group_first td {
  border-top-width: 2px;
}

#oyukdmcecw .gt_row_group_first th {
  border-top-width: 2px;
}

#oyukdmcecw .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#oyukdmcecw .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#oyukdmcecw .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#oyukdmcecw .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#oyukdmcecw .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#oyukdmcecw .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#oyukdmcecw .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#oyukdmcecw .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#oyukdmcecw .gt_table_body {
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #FFFFFF;
}

#oyukdmcecw .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#oyukdmcecw .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#oyukdmcecw .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#oyukdmcecw .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#oyukdmcecw .gt_left {
  text-align: left;
}

#oyukdmcecw .gt_center {
  text-align: center;
}

#oyukdmcecw .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#oyukdmcecw .gt_font_normal {
  font-weight: normal;
}

#oyukdmcecw .gt_font_bold {
  font-weight: bold;
}

#oyukdmcecw .gt_font_italic {
  font-style: italic;
}

#oyukdmcecw .gt_super {
  font-size: 65%;
}

#oyukdmcecw .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#oyukdmcecw .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#oyukdmcecw .gt_indent_1 {
  text-indent: 5px;
}

#oyukdmcecw .gt_indent_2 {
  text-indent: 10px;
}

#oyukdmcecw .gt_indent_3 {
  text-indent: 15px;
}

#oyukdmcecw .gt_indent_4 {
  text-indent: 20px;
}

#oyukdmcecw .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="true" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" style="color: #A9A9A9; font-family: 'Source Sans Pro'; text-transform: uppercase;" scope="col" id="model">model</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="color: #A9A9A9; font-family: 'Source Sans Pro'; text-transform: uppercase;" scope="col" id="rmse">rmse</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="model" class="gt_row gt_left" style="font-family: 'Source Sans Pro'; font-weight: 400;">standard</td>
<td headers="rmse" class="gt_row gt_right" style="color: #404040; font-family: 'Source Sans Pro'; font-weight: 400;">0.59</td></tr>
    <tr><td headers="model" class="gt_row gt_left" style="font-family: 'Source Sans Pro'; font-weight: 400;">median</td>
<td headers="rmse" class="gt_row gt_right" style="color: #404040; font-family: 'Source Sans Pro'; font-weight: 400;">0.59</td></tr>
    <tr><td headers="model" class="gt_row gt_left" style="font-family: 'Source Sans Pro'; font-weight: 400;">gam</td>
<td headers="rmse" class="gt_row gt_right" style="color: #404040; font-family: 'Source Sans Pro'; font-weight: 400;">0.59</td></tr>
    <tr><td headers="model" class="gt_row gt_left" style="font-family: 'Source Sans Pro'; font-weight: 400;">mixed</td>
<td headers="rmse" class="gt_row gt_right" style="color: #404040; font-family: 'Source Sans Pro'; font-weight: 400;">0.50</td></tr>
  </tbody>
  
  
</table>
</div>
<figcaption class="figure-caption">Figure&nbsp;6.10: Comparing model performance with RMSE</figcaption>
</figure>
</div>
</div>
<p>Let’s check out the results in <a href="#fig-model_performance_comp" class="quarto-xref">Figure&nbsp;<span>6.10</span></a>. Unsurprisingly, the standard linear model and the median regression were pretty close to each other. GAM offered a small bump in performance, but our best model came from the mixed model. This finding may or may not surprise you – as you spend more time with models, you often encounter situations where simple models outperform more complex models, or are on par with them. Here, we are seeing that the mixed model is offering us a better fit to the data than the other models. However, that doesn’t mean that you can just go right to the mixed model. You need to know your data and know what you are trying to accomplish.</p>
</section>
<section id="sec-lm-extend-wrap" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="sec-lm-extend-wrap"><span class="header-section-number">6.6</span> Wrapping Up</h2>
<p>The standard linear model is useful across many different data situations. It does, unfortunately, have some issues when data becomes a little bit more “real”. When you have extreme scores or relationships that a standard model might miss, you don’t need to abandon your linear model in favor of something more exotic. Instead, you might just need to think about how you are actually fitting the line through your data.</p>
</section>
<section id="sec-lm-extend-next-steps" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="sec-lm-extend-next-steps"><span class="header-section-number">6.7</span> Next Steps</h2>
<p>No matter how much we cover in this book, there is always more to learn. Here are some additional resources that you might find helpful related to this task. But if you’ve got a good grip on linear models and related topics, feel free to try out some machine learning <a href="machine_learning.html" class="quarto-xref"><span>Chapter&nbsp;7</span></a>!</p>
<p>If you want absolute depth on quantile regression, we will happily point you to the OG of quantile regression, Roger Koenker. His book, <em>Quantile Regression</em> is a must read for anyone wanting to dive deeper into quantile regression <span class="citation" data-cites="koenker_quantile_2005-1">(<a href="references.html#ref-koenker_quantile_2005-1" role="doc-biblioref">2005</a>)</span>, or just play around with his R package <code>quantreg</code>. <em>Galton, Edgeworth, Frisch, and prospects for quantile regression in econometrics</em> is another resource from him.</p>
<p>If you want to dive more into the GAM world, we would recommend that you start with the <strong>Moving Beyond Linearity</strong> chapter in <em>An Introduction to Statistical Learning</em> <span class="citation" data-cites="james_introduction_2021">(<a href="references.html#ref-james_introduction_2021" role="doc-biblioref">James et al. 2021</a>)</span>. Not only do they have versions for both R and Python, but both have been made <a href="https://www.statlearning.com/">available online</a>. If you are wanting more after that, you can’t beat Simon Wood’s book, <em>Generalized Additive Models: An Introduction with R</em> <span class="citation" data-cites="wood_generalized_2017">(<a href="references.html#ref-wood_generalized_2017" role="doc-biblioref">2017</a>)</span>, or a more digestible covering of the same content by one of your own humble authors <span class="citation" data-cites="clark_generalized_2022">(<a href="references.html#ref-clark_generalized_2022" role="doc-biblioref">Clark 2022</a>)</span>.</p>
<p>There is no shortage of great references for mixed effects models. If you are looking for a great introduction to mixed models, we would recommend to start with yet another tutorial by one of your fearless authors! Michael Clark’s <em>Mixed Models with R</em> <span class="citation" data-cites="clark_mixed_2023">(<a href="references.html#ref-clark_mixed_2023" role="doc-biblioref">2023</a>)</span>, is a great introduction to mixed models and is <a href="https://m-clark.github.io/mixed-models-with-R/">freely available</a>. If you want to dig just a little deeper, the <code>lme4</code> vignette for <a href="https://cran.r-project.org/web/packages/lme4/vignettes/lmer.pdf"><em>Fitting Linear Mixed-Effects Models Using lme4</em></a> is a great resource.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-clark_generalized_2022" class="csl-entry" role="listitem">
Clark, Michael J. 2022. <em>Generalized <span>Additive</span> <span>Models</span></em>. <a href="https://m-clark.github.io/generalized-additive-models/">https://m-clark.github.io/generalized-additive-models/</a>.
</div>
<div id="ref-clark_mixed_2023" class="csl-entry" role="listitem">
———. 2023. <em>Mixed <span>Models</span> with <span>R</span></em>. <a href="https://m-clark.github.io/mixed-models-with-R/">https://m-clark.github.io/mixed-models-with-R/</a>.
</div>
<div id="ref-james_introduction_2021" class="csl-entry" role="listitem">
James, Gareth, Daniela Witten, Trevor Hastie, and Robert Tibshirani. 2021. <em>An <span>Introduction</span> to <span>Statistical</span> <span>Learning</span></em>. Vol. 103. Springer <span>Texts</span> in <span>Statistics</span>. New York, NY: Springer New York. <a href="https://doi.org/10.1007/978-1-4614-7138-7">https://doi.org/10.1007/978-1-4614-7138-7</a>.
</div>
<div id="ref-koenker_quantile_2005-1" class="csl-entry" role="listitem">
Koenker, Roger. 2005. <em>Quantile Regression</em>. Vol. 38. Cambridge university press. <a href="https://books.google.com/books?hl=en&amp;lr=&amp;id=WjOdAgAAQBAJ&amp;oi=fnd&amp;pg=PT12&amp;dq=info:E32s5Y3j4NMJ:scholar.google.com&amp;ots=CQFHSt5qY_&amp;sig=E8zXmNabc0nGmYJlSYjQqhzyVT8">https://books.google.com/books?hl=en&amp;lr=&amp;id=WjOdAgAAQBAJ&amp;oi=fnd&amp;pg=PT12&amp;dq=info:E32s5Y3j4NMJ:scholar.google.com&amp;ots=CQFHSt5qY_&amp;sig=E8zXmNabc0nGmYJlSYjQqhzyVT8</a>.
</div>
<div id="ref-wood_generalized_2017" class="csl-entry" role="listitem">
Wood, Simon N. 2017. <em>Generalized <span>Additive</span> <span>Models</span>: <span>An</span> <span>Introduction</span> with <span>R</span>, <span>Second</span> <span>Edition</span></em>. 2nd ed. Boca Raton: Chapman; Hall/CRC. <a href="https://doi.org/10.1201/9781315370279">https://doi.org/10.1201/9781315370279</a>.
</div>
</div>
</section>
<aside id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>If we penalized the coefficients of the polynomial regression, we would have a penalized spline. It’s not used that much in GAMs these days, but there’s nothing wrong with doing so. See <a href="estimation.html#sec-estim-penalty" class="quarto-xref"><span>Section&nbsp;4.9</span></a> for more information on penalized regression.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>We used the <code>see</code> in R for a quick plot. We also recommend its functionality via the <code>gratia</code> package to visualize the derivatives, which will show more of where the effect is changing most.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</aside>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        for (let i = 0; i < 2; i++) {
          container.appendChild(note.children[i].cloneNode(true));
        }
        return container.innerHTML
      } else {
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        console.log("RESIZE");
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./generalized_linear_models.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Generalized Linear Models</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./machine_learning.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Core Concepts</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>