 Maybe you've encountered these concepts before, possibly in the first few weeks of a statistics course. You may have left that class confused, angry, and wondering why you would be subjected to such nonsense. If that sounds familiar, this chapter is for you.







Inversion

You might want to think of *matrix inversion* as the reciprocal of the matrix, usually noted as $A^{-1}$. The biggest reason that we might invert a matrix is because there is no matrix division.

Inversion can only be performed on square matrices (e.g., $2x2$, $3x3$, $4x4$) and the *determinant* of a matrix cannot be 0. Since the determinant is important for finding the inverse, we should probably have an idea about how to find the determinant.

### Matrix Determinant

While we've been using the matrix row/column positions in our examples, we are going to shift to letters to label the positions. We can start with a $2x2$ matrix:

$$
\stackrel{\mbox{Matrix C}}{
\begin{bmatrix}
A & B\\
C & D
\end{bmatrix}
}
$$

To find the determinant, we would take $\mid C \mid = (A*D) - (B*C)$.

Returning back to Matrix C, we have $\mid C \mid = (50_a*118_d) - (46_b*122_c) = 288$

$$
\stackrel{\mbox{Matrix C}}{
\begin{bmatrix}
50 & 46\\
122 & 118
\end{bmatrix}
}
$$

A $3x3$ matrix doesn't pose much more of a challenge. 

$$
\stackrel{\mbox{Matrix D}}{
\begin{bmatrix}
A & B & C\\
D & E & F\\
G & H & I
\end{bmatrix}
}
$$

The canonical form might not be as intuitive, but it is worth seeing:

$$
\mid D \mid = A\begin{vmatrix}
E & I\\
F & H
\end{vmatrix}  - 
B\begin{vmatrix}
D & I\\
F & G
\end{vmatrix} + 
C\begin{vmatrix}
D & H\\
E & G
\end{vmatrix}
$$

Breaking it down a bit further will help to see where all of the values go:

$$
\mid D \mid = A(E*I - F*H) - B(D*I - F*G) + C(D*H - E*G)
$$
Now we can work that out with a real matrix:

$$
\stackrel{\mbox{Matrix D}}{
\begin{bmatrix}
2 & 1 & 3\\
6 & 5 & 4\\
7 & 8 & 9
\end{bmatrix}
}
$$

To get our determinant:

$$
\mid D \mid = 2(5*9 - 4*8) - 1(6*9 - 4*7) + 3(6*8 - 5*7) = 39
$$

And just to confirm that our math is correct, we can check for the determinant in R and Python. 

R has a handy function called `det`:

```{r}
matrix_D = matrix(c(2, 1, 3,
                     6, 5, 4,
                     7, 8, 9), 
                   nrow = 3, 
                   ncol = 3, 
                   byrow = TRUE)

det(matrix_D)
```

We can keep using `numpy`, but we will have to use `det` within the `linalg` module.

```{python}
matrix_D = np.matrix('2 1 3; 6 5 4; 7 8 9')

np.linalg.det(matrix_D)
```

Just to show you how this pattern would continue

You can find a lot of examples online on how to do $2x2$ and $3x3$ matrix inversions, mostly because they are the easiest to do. 

How do you know that you properly inverted your matrix? You multiply the original matrix by the inverse matrix and you will get an *identity* matrix. 

We have a nice figure in Figure \@ref(fig:hello), and also a table in Table \@ref(tab:iris).